SUMO - Simulation of Urban MObility: MSNet Class Reference
MSNet Class Reference
The simulated network and simulation perfomer.
#include <MSNet.h>
Data Structures
class VehicleStateListener
Interface for objects listening to vehicle state changes.
Public Types
enum SimulationState {
SIMSTATE_RUNNING, SIMSTATE_END_STEP_REACHED, SIMSTATE_NO_FURTHER_VEHICLES, SIMSTATE_CONNECTION_CLOSED,
SIMSTATE_ERROR_IN_SIM, SIMSTATE_TOO_MANY_VEHICLES
}
Possible states of a simulation - running or stopped with different reasons.
Public Member Functions
void closeBuilding (MSEdgeControl *edges, MSJunctionControl *junctions, SUMORouteLoaderControl *routeLoaders, MSTLLogicControl *tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles)
Closes the network's building process.
void closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
SUMOTime getCurrentTimeStep () const
Returns the current simulation step (in s)
SUMOAbstractRouter< MSEdge,
SUMOVehicle > & getRouterEffort (const std::vector< MSEdge * > &prohibited=std::vector< MSEdge * >()) const
SUMOAbstractRouter< MSEdge,
SUMOVehicle > & getRouterTT (const std::vector< MSEdge * > &prohibited=std::vector< MSEdge * >()) const
void loadRoutes ()
loads routes for the next few steps
bool logSimulationDuration () const
Returns whether duration shall be logged.
MSNet (MSVehicleControl *vc, MSEventControl *beginOfTimestepEvents, MSEventControl *endOfTimestepEvents, MSEventControl *insertionEvents, ShapeContainer *shapeCont=0)
Constructor.
int simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
SimulationState simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
void simulationStep ()
Performs a single simulation step.
void writeOutput ()
Write netstate, summary and detector output.
virtual ~MSNet ()
Destructor.
Output during the simulation
void preSimStepOutput () const
Prints the current step number.
void postSimStepOutput () const
Prints the statistics of the step at its end.
Retrieval of references to substructures
MSVehicleControl & getVehicleControl ()
Returns the vehicle control.
virtual MSPersonControl & getPersonControl ()
Returns the person control.
MSEdgeControl & getEdgeControl ()
Returns the edge control.
MSInsertionControl & getInsertionControl ()
Returns the insertion control.
MSDetectorControl & getDetectorControl ()
Returns the detector control.
MSTLLogicControl & getTLSControl ()
Returns the tls logics control.
MSJunctionControl & getJunctionControl ()
Returns the junctions control.
MSEventControl & getBeginOfTimestepEvents ()
Returns the event control for events executed at the begin of a time step.
MSEventControl & getEndOfTimestepEvents ()
Returns the event control for events executed at the end of a time step.
MSEventControl & getInsertionEvents ()
Returns the event control for insertion events.
ShapeContainer & getShapeContainer ()
Returns the shapes container.
MSEdgeWeightsStorage & getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
Insertion and retrieval of bus stops
bool addBusStop (MSBusStop *busStop)
Adds a bus stop.
MSBusStop * getBusStop (const std::string &id) const
Returns the named bus stop.
std::string getBusStopID (const MSLane *lane, const SUMOReal pos) const
Returns the bus stop close to the given position.
Static Public Member Functions
static void clearAll ()
Clears all dictionaries.
static SUMOReal getEffort (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t)
Returns the effort to pass an edge.
static MSNet * getInstance ()
Returns the pointer to the unique instance of MSNet (singleton).
static std::string getStateMessage (SimulationState state)
Returns the message to show if a certain state occurs.
static SUMOReal getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t)
Returns the travel time to pass an edge.
Protected Attributes
NamedObjectCont< MSBusStop * > myBusStopDict
Dictionary of bus stops.
SUMORouteLoaderControl * myRouteLoaders
Route loader for dynamic loading of routes.
DijkstraRouterEffort_ByProxi
< MSEdge, SUMOVehicle,
prohibited_withRestrictions
< MSEdge, SUMOVehicle > > * myRouterEffort
AStarRouterTT_ByProxi< MSEdge,
SUMOVehicle,
prohibited_withRestrictions
< MSEdge, SUMOVehicle > > * myRouterTTAStar
DijkstraRouterTT_ByProxi
< MSEdge, SUMOVehicle,
prohibited_withRestrictions
< MSEdge, SUMOVehicle > > * myRouterTTDijkstra
bool myRouterTTInitialized
SUMOTime myStep
Current time step.
int myTooManyVehicles
Storage for maximum vehicle number.
std::vector
< VehicleStateListener * > myVehicleStateListeners
Container for vehicle state listener.
Substructures
MSVehicleControl * myVehicleControl
Controls vehicle building and deletion;.
MSPersonControl * myPersonControl
Controls person building and deletion;.
MSEdgeControl * myEdges
Controls edges, performs vehicle movement;.
MSJunctionControl * myJunctions
Controls junctions, realizes right-of-way rules;.
MSTLLogicControl * myLogics
Controls tls logics, realizes waiting on tls rules;.
MSInsertionControl * myInserter
Controls vehicle insertion;.
MSDetectorControl * myDetectorControl
Controls detectors;.
MSEventControl * myBeginOfTimestepEvents
Controls events executed at the begin of a time step;.
MSEventControl * myEndOfTimestepEvents
Controls events executed at the end of a time step;.
MSEventControl * myInsertionEvents
Controls insertion events;.
ShapeContainer * myShapeContainer
A container for geometrical shapes;.
MSEdgeWeightsStorage * myEdgeWeights
The net's knowledge about edge efforts/travel times;.
data needed for computing performance values
bool myLogExecutionTime
Information whether the simulation duration shall be logged.
bool myLogStepNumber
Information whether the number of the simulation step shall be logged.
long mySimStepBegin
The last simulation step begin, end and duration.
long mySimStepEnd
long mySimStepDuration
long mySimBeginMillis
The overall simulation duration.
SUMOLong myVehiclesMoved
The overall number of vehicle movements.
State output variables
std::vector< SUMOTime > myStateDumpTimes
Times at which a state shall be written.
std::vector< std::string > myStateDumpFiles
The names for the state files.
Static Protected Attributes
static MSNet * myInstance = 0
Unique instance of MSNet.
Private Member Functions
MSNet (const MSNet &)
Invalidated copy constructor.
MSNet & operator= (const MSNet &)
Invalidated assignment operator.
Notification about vehicle state changes
enum VehicleState {
VEHICLE_STATE_BUILT, VEHICLE_STATE_DEPARTED, VEHICLE_STATE_STARTING_TELEPORT, VEHICLE_STATE_ENDING_TELEPORT,
VEHICLE_STATE_ARRIVED, VEHICLE_STATE_NEWROUTE
}
Definition of a vehicle state.
void addVehicleStateListener (VehicleStateListener *listener)
Adds a vehicle states listener.
void removeVehicleStateListener (VehicleStateListener *listener)
Removes a vehicle states listener.
void informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
Detailed Description
The simulated network and simulation perfomer.
Definition at line 87 of file MSNet.h.
Member Enumeration Documentation
enum MSNet::SimulationState
Possible states of a simulation - running or stopped with different reasons.
Enumerator:
SIMSTATE_RUNNING
The simulation is running.
SIMSTATE_END_STEP_REACHED
The final simulation step has been performed.
SIMSTATE_NO_FURTHER_VEHICLES
The simulation does not contain further vehicles.
SIMSTATE_CONNECTION_CLOSED
The connection to a client was closed by the client.
SIMSTATE_ERROR_IN_SIM
An error occured during the simulation step.
SIMSTATE_TOO_MANY_VEHICLES
The simulation contains too many vehicles (.
Deprecated:
)
Definition at line 92 of file MSNet.h.
enum MSNet::VehicleState
Definition of a vehicle state.
Enumerator:
VEHICLE_STATE_BUILT
The vehicle was built, but has not yet departed.
VEHICLE_STATE_DEPARTED
The vehicle has departed (was inserted into the network)
VEHICLE_STATE_STARTING_TELEPORT
The vehicle started to teleport.
VEHICLE_STATE_ENDING_TELEPORT
The vehicle ended being teleported.
VEHICLE_STATE_ARRIVED
The vehicle arrived at his destination (is deleted)
VEHICLE_STATE_NEWROUTE
The vehicle got a new route.
Definition at line 405 of file MSNet.h.
Constructor & Destructor Documentation
MSNet::MSNet (MSVehicleControl * vc, MSEventControl * beginOfTimestepEvents, MSEventControl * endOfTimestepEvents, MSEventControl * insertionEvents, ShapeContainer * shapeCont = 0)
Constructor.
This constructor builds a net of which only some basic structures are initialised. It prepares the network for being filled while loading. As soon as all edge/junction/traffic lights and other containers are build, they must be initialised using "closeBuilding".
Parameters
[in] vc The vehicle control to use
[in] beginOfTimestepEvents The event control to use for simulation step begin events
[in] endOfTimestepEvents The event control to use for simulation step end events
[in] insertionEvents The event control to use for insertion events
[in] shapeCont The shape container to use
Exceptions
ProcessError If a network was already constructed
See Also
closeBuilding
Definition at line 158 of file MSNet.cpp.
References OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), OptionsCont::getString(), MSGlobals::gUseMesoSim, myBeginOfTimestepEvents, myDetectorControl, myEdges, myEdgeWeights, myEndOfTimestepEvents, myInserter, myInsertionEvents, myInstance, myJunctions, myLogExecutionTime, myLogics, myLogStepNumber, myPersonControl, myRouteLoaders, myShapeContainer, myStep, myTooManyVehicles, myVehicleControl, and string2time().
MSNet::~MSNet () virtual
Destructor.
Definition at line 224 of file MSNet.cpp.
References clearAll(), MSGlobals::gUseMesoSim, myBeginOfTimestepEvents, myDetectorControl, myEdges, myEdgeWeights, myEndOfTimestepEvents, myInserter, myInsertionEvents, myInstance, myJunctions, myLogics, myPersonControl, myRouteLoaders, myRouterEffort, myRouterTTAStar, myRouterTTDijkstra, myShapeContainer, and myVehicleControl.
MSNet::MSNet (const MSNet &) private
Invalidated copy constructor.
Member Function Documentation
bool MSNet::addBusStop (MSBusStop * busStop)
Adds a bus stop.
If another bus stop with the same id exists, false is returned. Otherwise, the bus stop is added to the internal bus stop container "myBusStopDict".
This control gets responsible for deletion of the added bus stop.
Parameters
[in] busStop The bus stop to add
Returns
Whether the bus stop could be added
Definition at line 678 of file MSNet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myBusStopDict.
Referenced by GUITriggerBuilder::buildBusStop(), and NLTriggerBuilder::buildBusStop().
void MSNet::addVehicleStateListener (VehicleStateListener * listener)
Adds a vehicle states listener.
Parameters
[in] listener The listener to add
Definition at line 651 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by MSDevice_Vehroutes::init(), and traci::TraCIServer::TraCIServer().
void MSNet::clearAll () static
Clears all dictionaries.
Todo:
Try to move all this to the destructor
Definition at line 487 of file MSNet.cpp.
References MSTrigger::cleanup(), MSCalibrator::cleanup(), MSDevice_Routing::cleanup(), MSRoute::clear(), MSLane::clear(), MSEdge::clear(), and MSVehicleTransfer::getInstance().
Referenced by GUILoadThread::run(), and ~MSNet().
void MSNet::closeBuilding (MSEdgeControl * edges, MSJunctionControl * junctions, SUMORouteLoaderControl * routeLoaders, MSTLLogicControl * tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles)
Closes the network's building process.
Assigns the structures built while loading to this network.
Parameters
[in] edges The control of edges which belong to this network
[in] junctions The control of junctions which belong to this network
[in] routeLoaders The route loaders used
[in] tlc The control of traffic lights which belong to this network
[in] stateDumpTimes List of time steps at which state shall be written
[in] stateDumpFiles Filenames for states
Todo:
Try to move all this to the constructor?
Definition at line 201 of file MSNet.cpp.
References SysUtils::getCurrentMillis(), myEdges, myJunctions, myLogExecutionTime, myLogics, myRouteLoaders, mySimBeginMillis, myStateDumpFiles, myStateDumpTimes, and MSJunctionControl::postloadInitContainer().
Referenced by NLBuilder::buildNet().
void MSNet::closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
Writes also performance output
Parameters
[in] start The step the simulation was started with
Todo:
What exceptions may occure?
Definition at line 308 of file MSNet.cpp.
References MSDetectorControl::close(), traci::TraCIServer::close(), MSDevice_Vehroutes::generateOutputForUnfinished(), MSVehicleControl::getCollisionCount(), SysUtils::getCurrentMillis(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSVehicleControl::getRunningVehicleNo(), MSVehicleControl::getTeleportCount(), MSInsertionControl::getWaitingVehicleNo(), myDetectorControl, myInserter, myLogExecutionTime, mySimBeginMillis, myStep, myVehicleControl, myVehiclesMoved, STEPS2TIME, SUMOReal, toString(), and WRITE_MESSAGE.
Referenced by GUIRunThread::deleteSim(), and simulate().
MSEventControl& MSNet::getBeginOfTimestepEvents () inline
Returns the event control for events executed at the begin of a time step.
Returns
The control reponsible for events that are executed at the begin of a time step
See Also
MSEventControl
myBeginOfTimestepEvents
Definition at line 319 of file MSNet.h.
References myBeginOfTimestepEvents.
Referenced by NLTriggerBuilder::buildVaporizer(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::closeWAUT(), MSLaneSpeedTrigger::init(), MSTrafficLightLogic::MSTrafficLightLogic(), MSDevice_Routing::notifyEnter(), and MSPerson::MSPersonStage_Walking::proceed().
MSBusStop * MSNet::getBusStop (const std::string & id) const
Returns the named bus stop.
Parameters
[in] id The id of the bus stop to return.
Returns
The named bus stop, or 0 if no such stop exists
Definition at line 684 of file MSNet.cpp.
References NamedObjectCont< T >::get(), and myBusStopDict.
Referenced by MSRouteHandler::addStop(), MSVehicle::addStop(), MSRouteHandler::myStartElement(), and TraCIServerAPI_Simulation::processGet().
std::string MSNet::getBusStopID (const MSLane * lane, const SUMOReal pos) const
Returns the bus stop close to the given position.
Parameters
[in] lane the lane of the bus stop to return.
[in] pos the position of the bus stop to return.
Returns
The bus stop id on the location, or "" if no such stop exists
Definition at line 690 of file MSNet.cpp.
References MSBusStop::getEndLanePosition(), Named::getID(), MSBusStop::getLane(), NamedObjectCont< T >::getMyMap(), myBusStopDict, and POSITION_EPS.
Referenced by MSVehicle::addTraciStop().
SUMOTime MSNet::getCurrentTimeStep () const
Returns the current simulation step (in s)
Returns
the current simulation step
Definition at line 500 of file MSNet.cpp.
References myStep.
Referenced by MSDevice_Vehroutes::addRoute(), MSTLLogicControl::addWAUTJunction(), NLDetectorBuilder::buildE2Detector(), MSVehicle::checkRewindLinkLanes(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSTLLogicControl::closeWAUT(), MSInductLoop::collectVehiclesOnDet(), traci::TraCIServer::commandAddVehicle(), TraCIServerAPI_Simulation::commandDistanceRequest(), GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSPersonControl::erase(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSActuatedTrafficLightLogic::gapControl(), MSInductLoop::getCurrentOccupancy(), GUIApplicationWindow::getCurrentSimTime(), MSLaneSpeedTrigger::getCurrentSpeed(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSLane::getLeaderOnConsecutive(), GUIApplicationWindow::handleEvent_SimulationLoaded(), GUIApplicationWindow::handleEvent_SimulationStep(), MSLaneSpeedTrigger::init(), traci::TraCIServer::initialiseSubscription(), MSTLLogicControl::initWautSwitch(), MSLane::isInsertionSuccess(), GUIRunThread::makeStep(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Person::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Person::notifyMove(), GUIApplicationWindow::onCmdTimeToggle(), MSBaseVehicle::onDepart(), traci::TraCIServer::postProcessSimulationStep2(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_TLS::processSet(), MSTrafficLightLogic::resetLinkStates(), GUIRunThread::run(), simulate(), MSSimpleTrafficLightLogic::trySwitch(), and MSActuatedTrafficLightLogic::trySwitch().
MSDetectorControl& MSNet::getDetectorControl () inline
Returns the detector control.
Returns
The detector control
See Also
MSDetectorControl
myDetectorControl
Definition at line 289 of file MSNet.h.
References myDetectorControl.
Referenced by NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), NLDetectorBuilder::createEdgeLaneMeanData(), NLDetectorBuilder::endE3Detector(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), TraCIServerAPI_InductionLoop::processGet(), and TraCIServerAPI_MeMeDetector::processGet().
MSEdgeControl& MSNet::getEdgeControl () inline
Returns the edge control.
Returns
The edge control
See Also
MSEdgeControl
myEdges
Definition at line 269 of file MSNet.h.
References myEdges.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), MSDevice_Routing::buildVehicleDevices(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), TraCIServerAPI_Vehicle::getOrBuildVTDMap(), TraCIServerAPI_Edge::getTree(), TraCIServerAPI_Lane::getTree(), MSLane::incorporateVehicle(), MSMeanData::init(), MSQueueExport::writeEdge(), and MSFullExport::writeEdge().
SUMOReal MSNet::getEffort (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) static
Returns the effort to pass an edge.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the effort shall be returned [s]
Returns
The effort (abstract) for an edge
See Also
DijkstraRouterTT_ByProxi
Definition at line 118 of file MSNet.cpp.
References getInstance(), MSVehicle::getWeightsStorage(), getWeightsStorage(), MSEdgeWeightsStorage::retrieveExistingEffort(), and SUMOReal.
Referenced by getRouterEffort().
MSEventControl& MSNet::getEndOfTimestepEvents () inline
Returns the event control for events executed at the end of a time step.
Returns
The control reponsible for events that are executed at the end of a time step
See Also
MSEventControl
myEndOfTimestepEvents
Definition at line 329 of file MSNet.h.
References myEndOfTimestepEvents.
Referenced by MSDevice_Routing::buildVehicleDevices(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), MSCalibrator::init(), and MSVTypeProbe::MSVTypeProbe().
MSInsertionControl& MSNet::getInsertionControl () inline
Returns the insertion control.
Returns
The insertion control
See Also
MSInsertionControl
myInserter
Definition at line 279 of file MSNet.h.
References myInserter.
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::closeVehicle(), GUINet::getParameterWindow(), MSLane::isInsertionSuccess(), MSPerson::MSPersonStage_Driving::proceed(), and TraCIServerAPI_Vehicle::processSet().
MSEventControl& MSNet::getInsertionEvents () inline
Returns the event control for insertion events.
Returns
The control reponsible for insertion events
See Also
MSEventControl
myInsertionEvents
Definition at line 339 of file MSNet.h.
References myInsertionEvents.
Referenced by MSDevice_Routing::MSDevice_Routing().
MSNet * MSNet::getInstance (void) static
Returns the pointer to the unique instance of MSNet (singleton).
Returns
Pointer to the unique MSNet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 150 of file MSNet.cpp.
References myInstance.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), MSInsertionControl::add(), MSTrafficLightLogic::addLink(), MSTLLogicControl::TLSLogicVariants::addLogic(), MSDevice_Vehroutes::addRoute(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStop(), MSVehicleTransfer::addVeh(), MSTLLogicControl::addWAUTJunction(), GUITrafficLightLogicWrapper::begin2TrackPhases(), NLTriggerBuilder::buildVaporizer(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSDevice_Routing::buildVehicleDevices(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSInsertionControl::checkFlows(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSTLLogicControl::closeWAUT(), MSInductLoop::collectVehiclesOnDet(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), traci::TraCIServer::commandAddVehicle(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), NLDetectorBuilder::createEdgeLaneMeanData(), MSLane::detectCollisions(), traci::TraCIServer::dispatchCommand(), GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUITrafficLightLogicWrapper::drawGL(), GUIPerson::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSDevice::equippedByDefaultAssignmentOptions(), MSPersonControl::erase(), MSCalibrator::execute(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSActuatedTrafficLightLogic::gapControl(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getCenteringBoundary(), GUIPerson::getColorValue(), GUILane::getColorValue(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSLaneSpeedTrigger::getCurrentSpeed(), MSInductLoop::getCurrentSpeed(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSInductLoop::getCurrentVehicleIDs(), getEffort(), GUINet::getGUIInstance(), MSLane::getLeaderOnConsecutive(), TraCIServerAPI_Vehicle::getOrBuildVTDMap(), MSTLLogicControl::getPhaseDef(), TraCIServerAPI_POI::getPoI(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_Junction::getPosition(), TraCIServerAPI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), GUILane::getStoredEdgeTravelTime(), MSInductLoop::getTimestepsSinceLastDetection(), getTravelTime(), TraCIServerAPI_InductionLoop::getTree(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Edge::getTree(), TraCIServerAPI_POI::getTree(), TraCIServerAPI_Lane::getTree(), TraCIServerAPI_Polygon::getTree(), MSLane::incorporateVehicle(), MSDevice_Vehroutes::init(), MSCalibrator::init(), MSLaneSpeedTrigger::init(), MSMeanData::init(), traci::TraCIServer::initialiseSubscription(), MSTLLogicControl::initWautSwitch(), MSLane::isInsertionSuccess(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSDevice_Routing::MSDevice_Routing(), MSTrafficLightLogic::MSTrafficLightLogic(), MSVTypeProbe::MSVTypeProbe(), MSRouteHandler::myEndElement(), MSRouteHandler::myStartElement(), MSStateHandler::myStartElement(), MSCalibrator::myStartElement(), MSDevice_Vehroutes::notifyEnter(), MSDevice_Person::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::notifyEnter(), MSDevice_Person::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSInstantInductLoop::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_Person::notifyMove(), MSInstantInductLoop::notifyMove(), MSE3Collector::MSE3EntryReminder::notifyMove(), MSInductLoop::notifyMove(), MSE3Collector::MSE3LeaveReminder::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), GUIViewTraffic::onGamingClick(), MSRouteHandler::openVehicleTypeDistribution(), MSVehicle::planMoveInternal(), traci::TraCIServer::postProcessSimulationStep2(), traci::TraCIServer::postProcessVTD(), MSPerson::MSPersonStage_Walking::proceed(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_MeMeDetector::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_VehicleType::processSet(), MSCalibrator::remainingVehicleCapacity(), MSVehicle::replaceRoute(), MSTrafficLightLogic::resetLinkStates(), MSStateHandler::saveState(), MSVehicleControl::scheduleVehicleRemoval(), GUIVehicle::setFunctionalColor(), MSLaneSpeedTrigger::setOverriding(), MSLaneSpeedTrigger::setOverridingValue(), traci::TraCIServer::TraCIServer(), MSSimpleTrafficLightLogic::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSVehicleControl::vehicleDeparted(), MSEmissionExport::write(), MSFCDExport::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), writeOutput(), MSFullExport::writeTLS(), MSFullExport::writeVehicles(), and traci::TraCIServer::~TraCIServer().
MSJunctionControl& MSNet::getJunctionControl () inline
Returns the junctions control.
Returns
The junctions control
See Also
MSJunctionControl
myJunctions
Definition at line 309 of file MSNet.h.
References myJunctions.
Referenced by TraCIServerAPI_Junction::getPosition(), TraCIServerAPI_Junction::getTree(), and TraCIServerAPI_Junction::processGet().
MSPersonControl & MSNet::getPersonControl () virtual
Returns the person control.
If the person control does not exist, yet, it is created.
Returns
The person control
See Also
MSPersonControl
myPersonControl
Reimplemented in GUINet.
Definition at line 602 of file MSNet.cpp.
References myPersonControl.
Referenced by MSRouteHandler::closePerson(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSDevice_Person::notifyLeave(), MSDevice_Person::notifyMove(), MSPerson::MSPersonStage_Walking::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPerson::MSPersonStage_Waiting::proceed(), and MSVehicle::processNextStop().
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterEffort (const std::vector< MSEdge * > & prohibited = std::vector<MSEdge*>()) const
Definition at line 730 of file MSNet.cpp.
References getEffort(), getTravelTime(), myRouterEffort, MSEdge::numericalDictSize(), and prohibited_withRestrictions< E, V >::prohibit().
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterTT (const std::vector< MSEdge * > & prohibited = std::vector<MSEdge*>()) const
Definition at line 703 of file MSNet.cpp.
References OptionsCont::getOptions(), OptionsCont::getString(), getTravelTime(), myRouterTTAStar, myRouterTTDijkstra, myRouterTTInitialized, MSEdge::numericalDictSize(), prohibited_withRestrictions< E, V >::prohibit(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), MSRouteHandler::myStartElement(), MSTriggeredRerouter::notifyEnter(), and TraCIServerAPI_Vehicle::processSet().
ShapeContainer& MSNet::getShapeContainer () inline
Returns the shapes container.
Returns
The shapes container
See Also
ShapeContainer
myShapeContainer
Definition at line 349 of file MSNet.h.
References myShapeContainer.
Referenced by NLHandler::addPOI(), NLHandler::addPoly(), TraCIServerAPI_POI::getPoI(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_POI::getTree(), TraCIServerAPI_Polygon::getTree(), GUISUMOViewParent::onCmdLocate(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
std::string MSNet::getStateMessage (MSNet::SimulationState state) static
Returns the message to show if a certain state occurs.
Returns
Readable description of the state
Definition at line 466 of file MSNet.cpp.
References SIMSTATE_CONNECTION_CLOSED, SIMSTATE_END_STEP_REACHED, SIMSTATE_ERROR_IN_SIM, SIMSTATE_NO_FURTHER_VEHICLES, SIMSTATE_RUNNING, and SIMSTATE_TOO_MANY_VEHICLES.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded(), GUIRunThread::makeStep(), and simulate().
MSTLLogicControl& MSNet::getTLSControl () inline
Returns the tls logics control.
Returns
The tls logics control
See Also
MSTLLogicControl
myLogics
Definition at line 299 of file MSNet.h.
References myLogics.
Referenced by NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), NLJunctionControlBuilder::getTLLogicControlToUse(), GUINet::initTLMap(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_TLS::processSet(), and MSFullExport::writeTLS().
SUMOReal MSNet::getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) static
Returns the travel time to pass an edge.
Parameters
[in] e The edge for which the travel time to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the travel time shall be returned [s]
Returns
The travel time for an edge
See Also
DijkstraRouterTT_ByProxi
Definition at line 132 of file MSNet.cpp.
References getInstance(), MSEdge::getMinimumTravelTime(), MSVehicle::getWeightsStorage(), getWeightsStorage(), MSEdgeWeightsStorage::retrieveExistingTravelTime(), and SUMOReal.
Referenced by MSDevice_Routing::buildVehicleDevices(), getRouterEffort(), and getRouterTT().
MSVehicleControl& MSNet::getVehicleControl () inline
Returns the vehicle control.
Returns
The vehicle control
See Also
MSVehicleControl
myVehicleControl
Definition at line 248 of file MSNet.h.
References myVehicleControl.
Referenced by MSInsertionControl::add(), MSVehicleTransfer::addVeh(), MSInsertionControl::checkFlows(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), traci::TraCIServer::commandAddVehicle(), MSLane::detectCollisions(), MSDevice::equippedByDefaultAssignmentOptions(), MSCalibrator::execute(), MSVTypeProbe::execute(), MSLane::executeMovements(), GUINet::getParameterWindow(), TraCIServerAPI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSStateHandler::myStartElement(), MSDevice_BTreceiver::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), MSRouteHandler::openVehicleTypeDistribution(), traci::TraCIServer::postProcessVTD(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_VehicleType::processSet(), MSCalibrator::remainingVehicleCapacity(), MSStateHandler::saveState(), GUINet::setSimDuration(), MSEmissionExport::write(), MSFCDExport::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), writeOutput(), and MSFullExport::writeVehicles().
MSEdgeWeightsStorage & MSNet::getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
If the net does not have such a container, it is built.
Returns
The net's knowledge about edge weights
Definition at line 611 of file MSNet.cpp.
References myEdgeWeights.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), GUILane::getColorValue(), getEffort(), GUILane::getStoredEdgeTravelTime(), getTravelTime(), and TraCIServerAPI_Edge::processSet().
void MSNet::informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
See Also
VehicleStateListener:vehicleStateChanged
Definition at line 668 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by MSVehicleTransfer::addVeh(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleTransfer::checkInsertions(), MSVehicle::replaceRoute(), MSVehicleControl::scheduleVehicleRemoval(), and MSVehicleControl::vehicleDeparted().
void MSNet::loadRoutes ()
loads routes for the next few steps
Definition at line 302 of file MSNet.cpp.
References SUMORouteLoaderControl::loadNext(), myRouteLoaders, and myStep.
Referenced by GUIRunThread::init(), simulate(), and simulationStep().
bool MSNet::logSimulationDuration () const
Returns whether duration shall be logged.
Returns
Whether duration shall be logged
Definition at line 596 of file MSNet.cpp.
References myLogExecutionTime.
Referenced by GUINet::getParameterWindow().
MSNet& MSNet::operator= (const MSNet &) private
Invalidated assignment operator.
void MSNet::postSimStepOutput () const
Prints the statistics of the step at its end.
Called on the end of a simulation step
Definition at line 626 of file MSNet.cpp.
References DELTA_T, MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getRunningVehicleNo(), myLogExecutionTime, mySimStepDuration, myStep, myVehicleControl, OUTPUT_ACCURACY, SUMOReal, and time2string().
Referenced by simulate().
void MSNet::preSimStepOutput () const
Prints the current step number.
Called on the begin of a simulation step
Definition at line 620 of file MSNet.cpp.
References myStep, and time2string().
Referenced by simulate().
void MSNet::removeVehicleStateListener (VehicleStateListener * listener)
Removes a vehicle states listener.
Parameters
[in] listener The listener to remove
Definition at line 659 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by traci::TraCIServer::~TraCIServer().
int MSNet::simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
Parameters
[in] start The begin time step of the simulation
[in] stop The end time step of the simulation
Returns
Returns always 0
Todo:
Recheck return value
What exceptions may occure?
Definition at line 257 of file MSNet.cpp.
References closeSimulation(), getCurrentTimeStep(), OptionsCont::getOptions(), getStateMessage(), loadRoutes(), myLogStepNumber, myStep, postSimStepOutput(), preSimStepOutput(), SIMSTATE_RUNNING, simulationState(), simulationStep(), time2string(), traci::TraCIServer::wasClosed(), and WRITE_MESSAGE.
Referenced by main().
MSNet::SimulationState MSNet::simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
Parameters
[in] stopTime The time the simulation shall stop at
Returns
The current simulation state
See Also
SimulationState
Definition at line 435 of file MSNet.cpp.
References MSPersonControl::abortWaiting(), MSVehicleControl::abortWaiting(), MSVehicleControl::getActiveVehicleCount(), OptionsCont::getInt(), OptionsCont::getOptions(), MSInsertionControl::getPendingFlowCount(), MSVehicleControl::getRunningVehicleNo(), MSPersonControl::hasNonWaiting(), MSEventControl::isEmpty(), myInserter, myInsertionEvents, myPersonControl, myStep, myTooManyVehicles, myVehicleControl, SIMSTATE_CONNECTION_CLOSED, SIMSTATE_END_STEP_REACHED, SIMSTATE_NO_FURTHER_VEHICLES, SIMSTATE_RUNNING, SIMSTATE_TOO_MANY_VEHICLES, and traci::TraCIServer::wasClosed().
Referenced by GUIRunThread::makeStep(), and simulate().
void MSNet::simulationStep ()
Performs a single simulation step.
Todo:
Which exceptions may occur?
Definition at line 347 of file MSNet.cpp.
References MSEdgeControl::changeLanes(), MSTLLogicControl::check2Switch(), MSVehicleTransfer::checkInsertions(), MSPersonControl::checkWaitingPersons(), DELTA_T, MSEdgeControl::detectCollisions(), MSInsertionControl::emitVehicles(), MSEventControl::execute(), MSEdgeControl::executeMovements(), MSGlobals::gCheck4Accidents, SysUtils::getCurrentMillis(), traci::TraCIServer::getInstance(), MSVehicleTransfer::getInstance(), MSVehicleControl::getRunningVehicleNo(), traci::TraCIServer::getTargetTime(), MSGlobals::gUseMesoSim, loadRoutes(), myBeginOfTimestepEvents, myEdges, myEndOfTimestepEvents, myInserter, myInsertionEvents, myLogExecutionTime, myLogics, myPersonControl, mySimStepBegin, mySimStepDuration, mySimStepEnd, myStateDumpFiles, myStateDumpTimes, myStep, myVehicleControl, myVehiclesMoved, MSEdgeControl::patchActiveLanes(), MSEdgeControl::planMovements(), traci::TraCIServer::postProcessVTD(), traci::TraCIServer::processCommandsUntilSimStep(), MSStateHandler::saveState(), and writeOutput().
Referenced by traci::TraCIServer::dispatchCommand(), simulate(), and GUINet::simulationStep().
void MSNet::writeOutput ()
Write netstate, summary and detector output.
Todo:
Which exceptions may occur?
Definition at line 506 of file MSNet.cpp.
References OutputDevice::closeTag(), DELTA_T, MSVehicleControl::getDepartedVehicleNo(), OutputDevice::getDeviceByOption(), MSEdgeControl::getEdges(), MSVehicleControl::getEndedVehicleNo(), getInstance(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSVehicleControl::getRunningVehicleNo(), OptionsCont::getString(), getVehicleControl(), MSInsertionControl::getWaitingVehicleNo(), myDetectorControl, myEdges, myInserter, myLogExecutionTime, mySimStepDuration, myStep, myVehicleControl, OutputDevice::openTag(), MSVehicleControl::printMeanTravelTime(), MSVehicleControl::printMeanWaitingTime(), STEPS2TIME, SUMO_ATTR_ID, time2string(), MSDetectorControl::updateDetectors(), MSVTKExport::write(), MSFCDExport::write(), MSEmissionExport::write(), MSQueueExport::write(), MSFullExport::write(), MSXMLRawOut::write(), OutputDevice::writeAttr(), and MSDetectorControl::writeOutput().
Referenced by simulationStep().
Field Documentation
MSEventControl* MSNet::myBeginOfTimestepEvents protected
Controls events executed at the begin of a time step;.
See Also
MSEventControl
Definition at line 521 of file MSNet.h.
Referenced by getBeginOfTimestepEvents(), MSNet(), simulationStep(), and ~MSNet().
NamedObjectCont<MSBusStop*> MSNet::myBusStopDict protected
Dictionary of bus stops.
Definition at line 570 of file MSNet.h.
Referenced by addBusStop(), getBusStop(), and getBusStopID().
MSDetectorControl* MSNet::myDetectorControl protected
Controls detectors;.
See Also
MSDetectorControl
Definition at line 519 of file MSNet.h.
Referenced by closeSimulation(), getDetectorControl(), GUINet::initGUIStructures(), MSNet(), writeOutput(), and ~MSNet().
MSEdgeControl* MSNet::myEdges protected
Controls edges, performs vehicle movement;.
See Also
MSEdgeControl
Definition at line 511 of file MSNet.h.
Referenced by closeBuilding(), getEdgeControl(), MSNet(), simulationStep(), writeOutput(), and ~MSNet().
MSEdgeWeightsStorage* MSNet::myEdgeWeights protected
The net's knowledge about edge efforts/travel times;.
See Also
MSEdgeWeightsStorage
Definition at line 529 of file MSNet.h.
Referenced by getWeightsStorage(), MSNet(), and ~MSNet().
MSEventControl* MSNet::myEndOfTimestepEvents protected
Controls events executed at the end of a time step;.
See Also
MSEventControl
Definition at line 523 of file MSNet.h.
Referenced by getEndOfTimestepEvents(), MSNet(), simulationStep(), and ~MSNet().
MSInsertionControl* MSNet::myInserter protected
Controls vehicle insertion;.
See Also
MSInsertionControl
Definition at line 517 of file MSNet.h.
Referenced by closeSimulation(), getInsertionControl(), MSNet(), simulationState(), simulationStep(), writeOutput(), and ~MSNet().
MSEventControl* MSNet::myInsertionEvents protected
Controls insertion events;.
See Also
MSEventControl
Definition at line 525 of file MSNet.h.
Referenced by getInsertionEvents(), MSNet(), simulationState(), simulationStep(), and ~MSNet().
MSNet * MSNet::myInstance = 0 static protected
Unique instance of MSNet.
Definition at line 493 of file MSNet.h.
Referenced by getInstance(), MSNet(), and ~MSNet().
MSJunctionControl* MSNet::myJunctions protected
Controls junctions, realizes right-of-way rules;.
See Also
MSJunctionControl
Definition at line 513 of file MSNet.h.
Referenced by closeBuilding(), getJunctionControl(), GUINet::getJunctionPosition(), GUINet::initGUIStructures(), MSNet(), and ~MSNet().
bool MSNet::myLogExecutionTime protected
Information whether the simulation duration shall be logged.
Definition at line 538 of file MSNet.h.
Referenced by closeBuilding(), closeSimulation(), logSimulationDuration(), MSNet(), postSimStepOutput(), simulationStep(), and writeOutput().
MSTLLogicControl* MSNet::myLogics protected
Controls tls logics, realizes waiting on tls rules;.
See Also
MSJunctionControl
Definition at line 515 of file MSNet.h.
Referenced by closeBuilding(), GUINet::createTLWrapper(), GUINet::getLinkTLID(), GUINet::getLinkTLIndex(), getTLSControl(), MSNet(), simulationStep(), and ~MSNet().
bool MSNet::myLogStepNumber protected
Information whether the number of the simulation step shall be logged.
Definition at line 541 of file MSNet.h.
Referenced by MSNet(), and simulate().
MSPersonControl* MSNet::myPersonControl protected
Controls person building and deletion;.
See Also
MSPersonControl
Definition at line 509 of file MSNet.h.
Referenced by GUINet::getPersonControl(), getPersonControl(), MSNet(), simulationState(), simulationStep(), and ~MSNet().
SUMORouteLoaderControl* MSNet::myRouteLoaders protected
Route loader for dynamic loading of routes.
Definition at line 496 of file MSNet.h.
Referenced by closeBuilding(), loadRoutes(), MSNet(), and ~MSNet().
DijkstraRouterEffort_ByProxi<MSEdge, SUMOVehicle, prohibited_withRestrictions<MSEdge, SUMOVehicle> >* MSNet::myRouterEffort mutable protected
Definition at line 583 of file MSNet.h.
Referenced by getRouterEffort(), and ~MSNet().
AStarRouterTT_ByProxi<MSEdge, SUMOVehicle, prohibited_withRestrictions<MSEdge, SUMOVehicle> >* MSNet::myRouterTTAStar mutable protected
Definition at line 582 of file MSNet.h.
Referenced by getRouterTT(), and ~MSNet().
DijkstraRouterTT_ByProxi<MSEdge, SUMOVehicle, prohibited_withRestrictions<MSEdge, SUMOVehicle> >* MSNet::myRouterTTDijkstra mutable protected
Definition at line 581 of file MSNet.h.
Referenced by getRouterTT(), and ~MSNet().
bool MSNet::myRouterTTInitialized mutable protected
Definition at line 580 of file MSNet.h.
Referenced by getRouterTT().
ShapeContainer* MSNet::myShapeContainer protected
A container for geometrical shapes;.
See Also
ShapeContainer
Definition at line 527 of file MSNet.h.
Referenced by getShapeContainer(), MSNet(), and ~MSNet().
long MSNet::mySimBeginMillis protected
The overall simulation duration.
Definition at line 547 of file MSNet.h.
Referenced by closeBuilding(), and closeSimulation().
long MSNet::mySimStepBegin protected
The last simulation step begin, end and duration.
Definition at line 544 of file MSNet.h.
Referenced by simulationStep().
long MSNet::mySimStepDuration protected
Definition at line 544 of file MSNet.h.
Referenced by postSimStepOutput(), simulationStep(), and writeOutput().
long MSNet::mySimStepEnd protected
Definition at line 544 of file MSNet.h.
Referenced by simulationStep().
std::vector<std::string> MSNet::myStateDumpFiles protected
The names for the state files.
Definition at line 561 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
std::vector<SUMOTime> MSNet::myStateDumpTimes protected
Times at which a state shall be written.
Definition at line 559 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
SUMOTime MSNet::myStep protected
Current time step.
Definition at line 499 of file MSNet.h.
Referenced by closeSimulation(), getCurrentTimeStep(), loadRoutes(), MSNet(), postSimStepOutput(), preSimStepOutput(), simulate(), simulationState(), simulationStep(), and writeOutput().
int MSNet::myTooManyVehicles protected
Storage for maximum vehicle number.
Definition at line 566 of file MSNet.h.
Referenced by MSNet(), and simulationState().
MSVehicleControl* MSNet::myVehicleControl protected
Controls vehicle building and deletion;.
See Also
MSVehicleControl
Definition at line 507 of file MSNet.h.
Referenced by closeSimulation(), GUINet::getGUIVehicleControl(), getVehicleControl(), MSNet(), postSimStepOutput(), simulationState(), simulationStep(), GUINet::vehicleExists(), writeOutput(), and ~MSNet().
SUMOLong MSNet::myVehiclesMoved protected
The overall number of vehicle movements.
Definition at line 550 of file MSNet.h.
Referenced by closeSimulation(), GUINet::getMeanUPS(), and simulationStep().
std::vector<VehicleStateListener*> MSNet::myVehicleStateListeners protected
Container for vehicle state listener.
Definition at line 573 of file MSNet.h.
Referenced by addVehicleStateListener(), informVehicleStateListener(), and removeVehicleStateListener().
The documentation for this class was generated from the following files:
MSNet.h
MSNet.cpp