SUMO - Simulation of Urban MObility: ToString.h File Reference
ToString.h File Reference
#include <config.h>
#include <sstream>
#include <string>
#include <iomanip>
#include <utils/xml/SUMOXMLDefinitions.h>
#include <utils/common/SUMOVehicleClass.h>
#include "StdDefs.h"
Functions
template<typename T , typename T_BETWEEN >
std::string joinToString (const std::vector< T > &v, const T_BETWEEN &between, std::streamsize accuracy=OUTPUT_ACCURACY)
template<typename T , typename T_BETWEEN >
std::string joinToString (const std::set< T > &s, const T_BETWEEN &between, std::streamsize accuracy=OUTPUT_ACCURACY)
template<class T >
std::string toString (const T &t, std::streamsize accuracy=OUTPUT_ACCURACY)
template<typename V >
std::string toString (const std::vector< V * > &v, std::streamsize accuracy=OUTPUT_ACCURACY)
template<>
std::string toString (const std::vector< int > &v, std::streamsize accuracy)
template<>
std::string toString (const std::vector< SUMOReal > &v, std::streamsize accuracy)
template<>
std::string toString (const std::set< std::string > &v, std::streamsize accuracy)
template<>
std::string toString< LaneSpreadFunction > (const LaneSpreadFunction &lsf, std::streamsize accuracy)
template<>
std::string toString< LinkDirection > (const LinkDirection &linkDir, std::streamsize accuracy)
template<>
std::string toString< LinkState > (const LinkState &linkState, std::streamsize accuracy)
template<>
std::string toString< SUMOVehicleClass > (const SUMOVehicleClass &vClass, std::streamsize accuracy)
template<>
std::string toString< SumoXMLAttr > (const SumoXMLAttr &attr, std::streamsize accuracy)
template<>
std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc &edgeFunc, std::streamsize accuracy)
template<>
std::string toString< SumoXMLNodeType > (const SumoXMLNodeType &nodeType, std::streamsize accuracy)
template<>
std::string toString< SumoXMLTag > (const SumoXMLTag &tag, std::streamsize accuracy)
template<>
std::string toString< TrafficLightType > (const TrafficLightType &type, std::streamsize accuracy)
Detailed Description
Author
Christian Roessel
Daniel Krajzewicz
Jakob Erdmann
Date
Wed, 23 Sep 2002
Version
Id:
ToString.h 14425 2013-08-16 20:11:47Z behrisch
Definition in file ToString.h.
Function Documentation
template<typename T , typename T_BETWEEN > std::string joinToString (const std::vector< T > & v, const T_BETWEEN & between, std::streamsize accuracy = OUTPUT_ACCURACY) inline
Definition at line 136 of file ToString.h.
References toString().
Referenced by getAllowedVehicleClassNames(), MSPerson::MSPersonStage_Driving::getStageTypeName(), Option_IntVector::getValueString(), NBNodeCont::joinJunctions(), NIImporter_DlrNavteq::NamesHandler::report(), toString(), and NWWriter_SUMO::writeRoundabout().
template<typename T , typename T_BETWEEN > std::string joinToString (const std::set< T > & s, const T_BETWEEN & between, std::streamsize accuracy = OUTPUT_ACCURACY) inline
Definition at line 164 of file ToString.h.
References toString().
template<class T > std::string toString (const T & t, std::streamsize accuracy = OUTPUT_ACCURACY) inline
Template for conversions from origin format to string representation (when supplied by c++/the stl)
Definition at line 51 of file ToString.h.
Referenced by MSDetectorControl::add(), ODMatrix::add(), NBLoadedSUMOTLDef::addConnection(), NIImporter_SUMO::addConnection(), NLHandler::addConnection(), NIImporter_SUMO::addEdge(), NIXMLEdgesHandler::addLane(), NLJunctionControlBuilder::addLogicItem(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimTL::NIVissimTLSignal::addTo(), NBNodeCont::analyzeCluster(), NIImporter_OpenStreetMap::RelationHandler::applyRestriction(), NLBuilder::build(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), NIImporter_OpenStreetMap::RelationHandler::checkEdgeRef(), MSInsertionControl::checkFlows(), RONet::checkFlows(), NBEdge::checkGeometry(), NGFrame::checkOptions(), NIFrame::checkOptions(), NLDetectorBuilder::checkSampleInterval(), MSNet::closeSimulation(), NBTrafficLightDefinition::collectAllLinks(), NBNetBuilder::compute(), DijkstraRouterTTBase< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), ODMatrix::computeDeparts(), NBNode::computeInternalLaneShape(), RODFNet::computeTypes(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NIXMLEdgesHandler::deleteEdge(), NIXMLNodesHandler::deleteNode(), NBTrafficLightLogic::deletePhase(), GUISelectedStorage::deselect(), MSLane::detectCollisions(), GUICalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUIVehicle::drawLinkItem(), GUILane::drawLinkNo(), GUILane::drawTLSLinkNo(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), MSE3Collector::enter(), OptionsLoader::error(), MSCalibrator::execute(), MSVehicle::executeMove(), OptionsLoader::fatalError(), NIImporter_OpenStreetMap::RelationHandler::findEdgeRef(), MSDevice_Example::generateOutput(), NIImporter_DlrNavteq::EdgesHandler::getColumn(), NLDetectorBuilder::getEdgeChecking(), NLDetectorBuilder::getLaneChecking(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), NIVissimDistrictConnection::getMeanSpeed(), GeomHelper::getNormal90D_CW(), GUISUMOAbstractView::getObjectsInBoundary(), GUIEdge::getPopUpMenu(), GUILane::getPopUpMenu(), Line::getPositionAtDistance(), Line::getPositionAtDistance2D(), ROEdge::getStoredEffort(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), ROEdge::getTravelTime(), TraCIServerAPI_VehicleType::getVariable(), NBNodeCont::guessTLs(), GUICompleteSchemeStorage::init(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::insertNodeChecking(), MSEdge::insertVehicle(), SUMOVehicleParameter::interpretEdgePos(), MSLane::isInsertionSuccess(), NBNodeCont::joinTLS(), joinToString(), MSE3Collector::leave(), NILoader::load(), PCLoaderVisum::load(), PCLoaderArcView::load(), NIImporter_ArcView::load(), NLBuilder::load(), NIImporter_OpenStreetMap::load(), NIImporter_RobocupRescue::loadEdges(), GUISelectedStorage::loadIDs(), PCLoaderOSM::loadIfSet(), MFXImageHelper::loadImage(), NIImporter_OpenDrive::loadNetwork(), NIImporter_RobocupRescue::loadNodes(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), main(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSRouteProbe::MSRouteProbe(), NIXMLEdgesHandler::myEndElement(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), GUISettingsHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::RelationHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), NIVissimAbstractEdge::NIVissimAbstractEdge(), GUIDialog_ViewSettings::onCmdColorChange(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIApplicationWindow::openNewView(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), PlainXMLFormatter::openTag(), OutputDevice_Network::OutputDevice_Network(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_Point(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), SUMOSAXReader::parseNext(), GUISettingsHandler::parseTextSettings(), ODMatrix::parseTimeLine(), SUMOVehicleParserHelper::parseVTypeEmbedded(), GUIVisualizationTextSettings::print(), NBNodeCont::printBuiltNodesStatistics(), TraCIServerAPI_Vehicle::processSet(), ODMatrix::readO(), NBNodeCont::removeSelfLoops(), MSBaseVehicle::replaceRouteEdges(), PCPolyContainer::report(), NIImporter_DlrNavteq::EdgesHandler::report(), NBRequest::reportWarnings(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RONet::saveAndRemoveRoutesUntil(), MSVehicle::saveState(), GUISelectedStorage::select(), RODFRouteCont::setID(), MFXAddEditTypedTable::setItemFromControl(), MFXAddEditTypedTable::setItemFromControl_NoRelease(), GeoConvHelper::setLoaded(), PositionVector::splitAt(), NBEdge::splitGeometry(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), GUISelectedStorage::toggleSelection(), traci::TraCIServer::TraCIServer(), NIXMLEdgesHandler::tryGetLaneSpread(), SAXWeightsHandler::tryParse(), GUISUMOAbstractView::updatePositionInformation(), NIXMLConnectionsHandler::validateLaneInfo(), OptionsLoader::warning(), MSFCDExport::write(), SUMOVTypeParameter::write(), MSInstantInductLoop::write(), SUMOVehicleParameter::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), PlainXMLFormatter::writeAttr(), BinaryFormatter::writeAttr(), NWWriter_SUMO::writeConnection(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), ODMatrix::writeFlows(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), GUICompleteSchemeStorage::writeSettings(), ROLoader::writeStats(), traci::TraCIServer::writeStatusCmd(), NWWriter_SUMO::writeSUMOTime(), MSFullExport::writeVehicles(), RORoute::writeXMLDefinition(), MSRouteProbe::writeXMLOutput(), MSCalibrator::writeXMLOutput(), GeoConvHelper::x2cartesian(), and SUMOAbstractRouter< ROEdge, ROVehicle >::~SUMOAbstractRouter().
template<typename V > std::string toString (const std::vector< V * > & v, std::streamsize accuracy = OUTPUT_ACCURACY) inline
Definition at line 122 of file ToString.h.
References UNUSED_PARAMETER.
template<> std::string toString (const std::vector< int > & v, std::streamsize accuracy) inline
Definition at line 152 of file ToString.h.
References joinToString().
template<> std::string toString (const std::vector< SUMOReal > & v, std::streamsize accuracy) inline
Definition at line 158 of file ToString.h.
References joinToString().
template<> std::string toString (const std::set< std::string > & v, std::streamsize accuracy) inline
Definition at line 179 of file ToString.h.
References joinToString().
template<> std::string toString< LaneSpreadFunction > (const LaneSpreadFunction & lsf, std::streamsize accuracy) inline
Definition at line 96 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LaneSpreadFunctions, and UNUSED_PARAMETER.
template<> std::string toString< LinkDirection > (const LinkDirection & linkDir, std::streamsize accuracy) inline
Definition at line 109 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LinkDirections, and UNUSED_PARAMETER.
template<> std::string toString< LinkState > (const LinkState & linkState, std::streamsize accuracy) inline
Definition at line 103 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LinkStates, and UNUSED_PARAMETER.
template<> std::string toString< SUMOVehicleClass > (const SUMOVehicleClass & vClass, std::streamsize accuracy) inline
Definition at line 89 of file ToString.h.
References SumoVehicleClassStrings, and UNUSED_PARAMETER.
template<> std::string toString< SumoXMLAttr > (const SumoXMLAttr & attr, std::streamsize accuracy) inline
Definition at line 68 of file ToString.h.
References SUMOXMLDefinitions::Attrs, StringBijection< T >::getString(), and UNUSED_PARAMETER.
template<> std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc & edgeFunc, std::streamsize accuracy) inline
Definition at line 82 of file ToString.h.
References SUMOXMLDefinitions::EdgeFunctions, StringBijection< T >::getString(), and UNUSED_PARAMETER.
template<> std::string toString< SumoXMLNodeType > (const SumoXMLNodeType & nodeType, std::streamsize accuracy) inline
Definition at line 75 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::NodeTypes, and UNUSED_PARAMETER.
template<> std::string toString< SumoXMLTag > (const SumoXMLTag & tag, std::streamsize accuracy) inline
Definition at line 61 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::Tags, and UNUSED_PARAMETER.
template<> std::string toString< TrafficLightType > (const TrafficLightType & type, std::streamsize accuracy) inline
Definition at line 115 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::TrafficLightTypes, and UNUSED_PARAMETER.