SUMO - Simulation of Urban MObility: MSBusStop Class Reference
MSBusStop Class Reference
A lane area vehicles can halt at.
#include <MSBusStop.h>
Public Member Functions
void addPerson (MSPerson *p)
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void enter (SUMOVehicle *what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
SUMOReal getBeginLanePosition () const
Returns the begin position of this bus stop.
SUMOReal getEndLanePosition () const
Returns the end position of this bus stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this bus stop is located at.
SUMOReal getLastFreePos (const SUMOVehicle &forVehicle) const
Returns the last free position on this stop.
unsigned int getPersonNumber () const
Returns the number of persons waiting on this stop.
void leaveFrom (SUMOVehicle *what)
Called if a vehicle leaves this stop.
MSBusStop (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, SUMOReal begPos, SUMOReal endPos)
Constructor.
void removePerson (MSPerson *p)
void setID (const std::string &newID)
resets the id
virtual ~MSBusStop ()
Destructor.
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
Protected Attributes
SUMOReal myBegPos
The begin position this bus stop is located at.
SUMOReal myEndPos
The end position this bus stop is located at.
std::map< SUMOVehicle
*, std::pair< SUMOReal,
SUMOReal > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
MSLane & myLane
The lane this bus stop is located at.
SUMOReal myLastFreePos
The last free position at this stop (variable)
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
std::vector< MSPerson * > myWaitingPersons
Persons waiting at this stop.
Private Member Functions
MSBusStop (const MSBusStop &)
Invalidated copy constructor.
MSBusStop & operator= (const MSBusStop &)
Invalidated assignment operator.
Detailed Description
A lane area vehicles can halt at.
The bus stops tracks the last free space a vehicle may halt at by being informed about a vehicle's entering and depart. It keeps the information about entered vehicles' begin and end position within an internal container ("myEndPositions") and is so able to compute the last free space.
Please note that using the last free space disallows vehicles to enter a free space in between other vehicles.
Definition at line 63 of file MSBusStop.h.
Constructor & Destructor Documentation
MSBusStop::MSBusStop (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, SUMOReal begPos, SUMOReal endPos)
Constructor.
Parameters
[in] id The id of the bus stop
[in] net The net the bus stop belongs to
[in] lines Names of the bus lines that halt on this bus stop
[in] lane The lane the bus stop is placed on
[in] begPos Begin position of the bus stop on the lane
[in] endPos End position of the bus stop on the lane
Definition at line 45 of file MSBusStop.cpp.
References computeLastFreePos().
MSBusStop::~MSBusStop () virtual
Destructor.
Definition at line 55 of file MSBusStop.cpp.
MSBusStop::MSBusStop (const MSBusStop &) private
Invalidated copy constructor.
Member Function Documentation
void MSBusStop::addPerson (MSPerson * p) inline
Definition at line 143 of file MSBusStop.h.
References myWaitingPersons.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 114 of file Named.h.
References Named::StoringVisitor::add().
void MSBusStop::computeLastFreePos () protected
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 101 of file MSBusStop.cpp.
References myEndPos, myEndPositions, and myLastFreePos.
Referenced by enter(), leaveFrom(), and MSBusStop().
void MSBusStop::enter (SUMOVehicle * what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See Also
computeLastFreePos
Definition at line 77 of file MSBusStop.cpp.
References computeLastFreePos(), and myEndPositions.
Referenced by MSVehicle::processNextStop().
SUMOReal MSBusStop::getBeginLanePosition () const
Returns the begin position of this bus stop.
Returns
The position the bus stop begins at
Definition at line 65 of file MSBusStop.cpp.
References myBegPos.
Referenced by MSRouteHandler::addStop(), and MSVehicle::processNextStop().
SUMOReal MSBusStop::getEndLanePosition () const
Returns the end position of this bus stop.
Returns
The position the bus stop ends at
Definition at line 71 of file MSBusStop.cpp.
References myEndPos.
Referenced by MSRouteHandler::addStop(), MSPerson::MSPersonStage_Walking::computeWalkingTime(), and MSNet::getBusStopID().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NBEdge::connections_sorter(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), RODFNet::getDetectorEdge(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), AGStreet::getName(), NIImporter_VISUM::getNamedEdgeContinuating(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), RODFDetectorCon::guessEmptyFlows(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), NBEdgeCont::ignoreFilterMatch(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), NBRampsComputer::moveRampRight(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), MSVehicle::MSVehicle(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Person::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), AGStreet::print(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), GUITrafficLightLogicWrapper::switchTLSLogic(), NIXMLConnectionsHandler::validateLaneInfo(), TraCIServerAPI_Vehicle::vtdMap_matchingEdgeLane(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane & MSBusStop::getLane () const
Returns the lane this bus stop is located at.
Returns
Reference to the lane the bus stop is located at
Definition at line 59 of file MSBusStop.cpp.
References myLane.
Referenced by MSRouteHandler::addStop(), and MSNet::getBusStopID().
SUMOReal MSBusStop::getLastFreePos (const SUMOVehicle & forVehicle) const
Returns the last free position on this stop.
Returns
The last free position of this bus stop
Definition at line 84 of file MSBusStop.cpp.
References MSVehicleType::getMinGap(), SUMOVehicle::getVehicleType(), myEndPos, and myLastFreePos.
Referenced by MSVehicle::planMoveInternal(), and MSVehicle::processNextStop().
unsigned int MSBusStop::getPersonNumber () const inline
Returns the number of persons waiting on this stop.
Definition at line 139 of file MSBusStop.h.
References myWaitingPersons.
Referenced by GUIBusStop::getParameterWindow(), and TraCIServerAPI_Simulation::processGet().
void MSBusStop::leaveFrom (SUMOVehicle * what)
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that leaves the bus stop
See Also
computeLastFreePos
Definition at line 93 of file MSBusStop.cpp.
References computeLastFreePos(), and myEndPositions.
Referenced by MSVehicle::processNextStop().
MSBusStop& MSBusStop::operator= (const MSBusStop &) private
Invalidated assignment operator.
void MSBusStop::removePerson (MSPerson * p) inline
Definition at line 147 of file MSBusStop.h.
References myWaitingPersons.
Referenced by MSVehicle::processNextStop().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
Field Documentation
SUMOReal MSBusStop::myBegPos protected
The begin position this bus stop is located at.
Definition at line 175 of file MSBusStop.h.
Referenced by getBeginLanePosition(), and GUIBusStop::getParameterWindow().
SUMOReal MSBusStop::myEndPos protected
The end position this bus stop is located at.
Definition at line 178 of file MSBusStop.h.
Referenced by computeLastFreePos(), getEndLanePosition(), getLastFreePos(), and GUIBusStop::getParameterWindow().
std::map<SUMOVehicle*, std::pair<SUMOReal, SUMOReal> > MSBusStop::myEndPositions protected
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 169 of file MSBusStop.h.
Referenced by computeLastFreePos(), enter(), and leaveFrom().
std::string Named::myID protected inherited
The name of the object.
Definition at line 121 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), MSE3Collector::writeXMLOutput(), and MSMeanData::writeXMLOutput().
MSLane& MSBusStop::myLane protected
The lane this bus stop is located at.
Definition at line 172 of file MSBusStop.h.
Referenced by getLane().
SUMOReal MSBusStop::myLastFreePos protected
The last free position at this stop (variable)
Definition at line 181 of file MSBusStop.h.
Referenced by computeLastFreePos(), and getLastFreePos().
std::vector<std::string> MSBusStop::myLines protected
The list of lines that are assigned to this stop.
Definition at line 166 of file MSBusStop.h.
Referenced by GUIBusStop::drawGL().
std::vector<MSPerson*> MSBusStop::myWaitingPersons protected
Persons waiting at this stop.
Definition at line 184 of file MSBusStop.h.
Referenced by addPerson(), GUIBusStop::drawGL(), getPersonNumber(), and removePerson().
The documentation for this class was generated from the following files:
MSBusStop.h
MSBusStop.cpp