SUMO - Simulation of Urban MObility: TraCIServerAPI_Lane Class Reference
TraCIServerAPI_Lane Class Reference
APIs for getting/setting lane values via TraCI.
#include <TraCIServerAPI_Lane.h>
Static Public Member Functions
static bool getShape (const std::string &id, PositionVector &shape)
Returns the named lane's shape.
static TraCIRTree * getTree ()
Returns a tree filled with inductive loop instances.
static bool processGet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa3: Get Lane Variable)
static bool processSet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc3: Change Lane State)
Private Member Functions
TraCIServerAPI_Lane & operator= (const TraCIServerAPI_Lane &s)
invalidated assignment operator
TraCIServerAPI_Lane (const TraCIServerAPI_Lane &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting lane values via TraCI.
Definition at line 48 of file TraCIServerAPI_Lane.h.
Constructor & Destructor Documentation
TraCIServerAPI_Lane::TraCIServerAPI_Lane (const TraCIServerAPI_Lane & s) private
invalidated copy constructor
Member Function Documentation
bool TraCIServerAPI_Lane::getShape (const std::string & id, PositionVector & shape) static
Returns the named lane's shape.
Parameters
[in] id The id of the searched lane
[out] shape The shape, if the lane is known
Returns
Whether the lane is known
Definition at line 349 of file TraCIServerAPI_Lane.cpp.
References MSLane::dictionary(), MSLane::getShape(), and PositionVector::push_back().
Referenced by traci::TraCIServer::findObjectShape().
TraCIRTree * TraCIServerAPI_Lane::getTree () static
Returns a tree filled with inductive loop instances.
Returns
The rtree of inductive loop
Definition at line 360 of file TraCIServerAPI_Lane.cpp.
References TraCIRTree::addObject(), MSNet::getEdgeControl(), MSEdgeControl::getEdges(), MSNet::getInstance(), and Boundary::grow().
Referenced by traci::TraCIServer::collectObjectsInRange().
TraCIServerAPI_Lane& TraCIServerAPI_Lane::operator= (const TraCIServerAPI_Lane & s) private
invalidated assignment operator
bool TraCIServerAPI_Lane::processGet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa3: Get Lane Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 58 of file TraCIServerAPI_Lane.cpp.
References CMD_GET_LANE_VARIABLE, DEFAULT_VEH_DECEL, DEFAULT_VEH_LENGTH, MSLane::dictionary(), getAllowedVehicleClassNamesList(), MSNet::getCurrentTimeStep(), MSLink::getDirection(), MSLane::getEdge(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHBEFA_CO2Emissions(), MSLane::getHBEFA_COEmissions(), MSLane::getHBEFA_FuelConsumption(), MSLane::getHBEFA_HCEmissions(), MSLane::getHBEFA_NOxEmissions(), MSLane::getHBEFA_PMxEmissions(), Named::getID(), MSNet::getInstance(), MSLink::getLane(), MSLink::getLength(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getMeanSpeed(), MSLane::getOccupancy(), MSLane::getPermissions(), MSLane::getShape(), MSLane::getSpeedLimit(), MSLink::getState(), MSLane::getVehicleNumber(), MSLane::getVehiclesSecure(), MSLane::getWidth(), MSLink::hasApproachingFoe(), MSLink::havePriority(), ID_COUNT, ID_LIST, MSLane::insertIDs(), LANE_ALLOWED, LANE_DISALLOWED, LANE_EDGE_ID, LANE_LINK_NUMBER, LANE_LINKS, LAST_STEP_LENGTH, LAST_STEP_MEAN_SPEED, LAST_STEP_OCCUPANCY, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, SUMOXMLDefinitions::LinkDirections, SUMOXMLDefinitions::LinkStates, MIN2(), MSLink::opened(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), MSLane::releaseVehicles(), RESPONSE_GET_LANE_VARIABLE, RTYPE_OK, SUMO_const_haltingSpeed, SUMOReal, SVCFreeForAll, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, TYPE_UBYTE, VAR_CO2EMISSION, VAR_COEMISSION, VAR_CURRENT_TRAVELTIME, VAR_FUELCONSUMPTION, VAR_HCEMISSION, VAR_LENGTH, VAR_MAXSPEED, VAR_NOISEEMISSION, VAR_NOXEMISSION, VAR_PMXEMISSION, VAR_SHAPE, VAR_WIDTH, tcpip::Storage::writeDouble(), traci::TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), traci::TraCIServer::writeResponseWithLength(), traci::TraCIServer::writeStatusCmd(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by traci::TraCIServer::TraCIServer().
bool TraCIServerAPI_Lane::processSet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc3: Change Lane State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 290 of file TraCIServerAPI_Lane.cpp.
References CMD_SET_LANE_VARIABLE, MSLane::dictionary(), MSLane::getEdge(), LANE_ALLOWED, LANE_DISALLOWED, parseVehicleClasses(), tcpip::Storage::readString(), traci::TraCIServer::readTypeCheckingDouble(), traci::TraCIServer::readTypeCheckingStringList(), tcpip::Storage::readUnsignedByte(), MSEdge::rebuildAllowedLanes(), RTYPE_OK, MSLane::setLength(), MSLane::setMaxSpeed(), MSLane::setPermissions(), VAR_LENGTH, VAR_MAXSPEED, traci::TraCIServer::writeErrorStatusCmd(), and traci::TraCIServer::writeStatusCmd().
Referenced by traci::TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_Lane.h
TraCIServerAPI_Lane.cpp