SUMO - Simulation of Urban MObility: SUMORTree Class Reference
SUMORTree Class Reference
A RT-tree for efficient storing of SUMO's GL-objects.
#include <SUMORTree.h>
Public Member Functions
void add (SUMOReal x, SUMOReal y)
Makes the boundary include the given coordinate.
void add (const Position &p)
Makes the boundary include the given coordinate.
void add (const Boundary &p)
Makes the boundary include the given boundary.
void addAdditionalGLObject (GUIGlObject *o)
Adds an additional object (detector/shape/trigger) for visualisation.
bool around (const Position &p, SUMOReal offset=0) const
Returns whether the boundary contains the given coordinate.
bool crosses (const Position &p1, const Position &p2) const
Returns whether the boundary crosses the given line.
void flipY ()
flips ymin and ymax
Position getCenter () const
Returns the center of the boundary.
SUMOReal getHeight () const
Returns the height of the boundary.
SUMOReal getWidth () const
Returns the width of the boudary.
Boundary & grow (SUMOReal by)
extends the boundary by the given amount
void growHeight (SUMOReal by)
void growWidth (SUMOReal by)
virtual void Insert (const float a_min[2], const float a_max[2], GUIGlObject *a_dataId)
Insert entry.
void moveby (SUMOReal x, SUMOReal y)
Moves the boundary by the given amount.
bool overlapsWith (const AbstractPoly &poly, SUMOReal offset=0) const
Returns whether the boundary overlaps with the given polygon.
bool partialWithin (const AbstractPoly &poly, SUMOReal offset=0) const
Returns whether the boundary is partially within the given polygon.
virtual void Remove (const float a_min[2], const float a_max[2], GUIGlObject *a_dataId)
Remove entry.
void removeAdditionalGLObject (GUIGlObject *o)
Removes an additional object (detector/shape/trigger) from being visualised.
void reset ()
Resets the boundary.
virtual int Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings &c)
Find all within search rectangle.
void set (SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax)
Sets the boundary to the given values.
SUMORTree ()
Constructor.
SUMOReal xmax () const
Returns maximum x-coordinate.
SUMOReal xmin () const
Returns minimum x-coordinate.
SUMOReal ymax () const
Returns maximum y-coordinate.
SUMOReal ymin () const
Returns minimum y-coordinate.
virtual ~SUMORTree ()
Destructor.
Protected Attributes
MFXMutex myLock
A mutex avoiding parallel change and traversal of the tree.
Private Types
enum
typedef void(GUIGlObject::* Operation)(const GUIVisualizationSettings &) const
Private Member Functions
bool AddBranch (Branch *a_branch, Node *a_node, Node **a_newNode)
ListNode * AllocListNode ()
Node * AllocNode ()
float CalcRectVolume (Rect *a_rect)
void ChoosePartition (PartitionVars *a_parVars, int a_minFill)
void Classify (int a_index, int a_group, PartitionVars *a_parVars)
Rect CombineRect (Rect *a_rectA, Rect *a_rectB)
int Count ()
Count the data elements in this container. This is slow as no internal counter is maintained.
void CountRec (Node *a_node, int &a_count)
void DisconnectBranch (Node *a_node, int a_index)
void FreeListNode (ListNode *a_listNode)
void FreeNode (Node *a_node)
GUIGlObject *& GetAt (Iterator &a_it)
Get object at iterator position.
void GetBranches (Node *a_node, Branch *a_branch, PartitionVars *a_parVars)
void GetFirst (Iterator &a_it)
Get 'first' for iteration.
void GetNext (Iterator &a_it)
Get Next for iteration.
void InitNode (Node *a_node)
void InitParVars (PartitionVars *a_parVars, int a_maxRects, int a_minFill)
void InitRect (Rect *a_rect)
virtual void Insert (const floata_min[NUMDIMS], const floata_max[NUMDIMS], const GUIGlObject *&a_dataId)
bool InsertRect (Rect *a_rect, const GUIGlObject *&a_id, Node **a_root, int a_level)
bool InsertRectRec (Rect *a_rect, const GUIGlObject *&a_id, Node *a_node, Node **a_newNode, int a_level)
bool IsNull (Iterator &a_it)
Is iterator NULL, or at end?
void LoadNodes (Node *a_nodeA, Node *a_nodeB, PartitionVars *a_parVars)
Rect NodeCover (Node *a_node)
bool Overlap (Rect *a_rectA, Rect *a_rectB)
int PickBranch (Rect *a_rect, Node *a_node)
void PickSeeds (PartitionVars *a_parVars)
float RectSphericalVolume (Rect *a_rect)
float RectVolume (Rect *a_rect)
void ReInsert (Node *a_node, ListNode **a_listNode)
virtual void Remove (const floata_min[NUMDIMS], const floata_max[NUMDIMS], const GUIGlObject *&a_dataId)
void RemoveAll ()
DK 15.10.2008 - end.
void RemoveAllRec (Node *a_node)
bool RemoveRect (Rect *a_rect, const GUIGlObject *&a_id, Node **a_root)
bool RemoveRectRec (Rect *a_rect, const GUIGlObject *&a_id, Node *a_node, ListNode **a_listNode)
void Reset ()
virtual int Search (const floata_min[NUMDIMS], const floata_max[NUMDIMS], const GUIVisualizationSettings &c)
DK 15.10.2008 - begin.
bool Search (Node *a_node, Rect *a_rect, int &a_foundCount, const GUIVisualizationSettings &c)
void SplitNode (Node *a_node, Branch *a_branch, Node **a_newNode)
Private Attributes
Node * m_root
Root of tree.
float m_unitSphereVolume
Unit sphere constant for required number of dimensions.
Operation myOperation
Detailed Description
A RT-tree for efficient storing of SUMO's GL-objects.
This class specialises the used RT-tree implementation from "rttree.h" and extends it by a mutex for avoiding parallel change and traversal of the tree.
Definition at line 61 of file SUMORTree.h.
Member Typedef Documentation
typedef void(GUIGlObject ::* RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Operation)(const GUIVisualizationSettings &) const inherited
Definition at line 79 of file RTree.h.
Member Enumeration Documentation
anonymous enum inherited
Definition at line 71 of file RTree.h.
Constructor & Destructor Documentation
SUMORTree::SUMORTree () inline
Constructor.
Definition at line 65 of file SUMORTree.h.
Referenced by LayeredRTree::LayeredRTree().
virtual SUMORTree::~SUMORTree () inline virtual
Destructor.
Definition at line 71 of file SUMORTree.h.
Member Function Documentation
void Boundary::add (SUMOReal x, SUMOReal y) inherited
Makes the boundary include the given coordinate.
Definition at line 76 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::NodeSubCluster::add(), NIVissimConnectionCluster::add(), TraCIRTree::addObject(), Boundary::Boundary(), GUIDanielPerspectiveChanger::centerTo(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), GUIEdge::getBoundary(), PositionVector::getBoxBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GUIVehicle::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), TraCIServerAPI_Edge::getTree(), GUICalibrator::GUICalibrator(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), GUITriggeredRerouter::GUITriggeredRerouter(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), GUINet::initGUIStructures(), NBNetBuilder::moveToOrigin(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::MyWrapper(), GUIE3Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), NIVissimConnectionCluster::recomputeBoundary(), NIVissimNodeDef_Edges::searchAndSetConnections(), GUIDanielPerspectiveChanger::setViewport(), and GeoConvHelper::x2cartesian().
void Boundary::add (const Position & p) inherited
Makes the boundary include the given coordinate.
Definition at line 93 of file Boundary.cpp.
References Boundary::add(), Position::x(), and Position::y().
void Boundary::add (const Boundary & p) inherited
Makes the boundary include the given boundary.
Definition at line 99 of file Boundary.cpp.
References Boundary::add(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
void SUMORTree::addAdditionalGLObject (GUIGlObject * o) inline
Adds an additional object (detector/shape/trigger) for visualisation.
Parameters
[in] o The object to add
Definition at line 117 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), Insert(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIShapeContainer::addPOI(), GUIShapeContainer::addPolygon(), GUINet::createTLWrapper(), GUITriggeredRerouter::GUITriggeredRerouter(), GUINet::initGUIStructures(), GUIShapeContainer::movePOI(), and GUIShapeContainer::reshapePolygon().
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::AddBranch (Branch * a_branch, Node * a_node, Node ** a_newNode) protected inherited
ListNode* RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::AllocListNode () protected inherited
Node* RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::AllocNode () protected inherited
bool Boundary::around (const Position & p, SUMOReal offset = 0) const virtual inherited
Returns whether the boundary contains the given coordinate.
Implements AbstractPoly.
Definition at line 148 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Position::x(), and Position::y().
Referenced by NIVissimConnectionCluster::around(), PCPolyContainer::insert(), and NIVissimConnectionCluster::recheckEdges().
float RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::CalcRectVolume (Rect * a_rect) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::ChoosePartition (PartitionVars * a_parVars, int a_minFill) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Classify (int a_index, int a_group, PartitionVars * a_parVars) protected inherited
Rect RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::CombineRect (Rect * a_rectA, Rect * a_rectB) protected inherited
int RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Count () inherited
Count the data elements in this container. This is slow as no internal counter is maintained.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::CountRec (Node * a_node, int & a_count) protected inherited
bool Boundary::crosses (const Position & p1, const Position & p2) const virtual inherited
Returns whether the boundary crosses the given line.
Implements AbstractPoly.
Definition at line 177 of file Boundary.cpp.
References GeomHelper::intersects(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::DisconnectBranch (Node * a_node, int a_index) protected inherited
void Boundary::flipY () inherited
flips ymin and ymax
Definition at line 222 of file Boundary.cpp.
References Boundary::myYmax, Boundary::myYmin, and SUMOReal.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::FreeListNode (ListNode * a_listNode) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::FreeNode (Node * a_node) protected inherited
GUIGlObject * & RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::GetAt (Iterator & a_it) inline inherited
Get object at iterator position.
Definition at line 263 of file RTree.h.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::GetBranches (Node * a_node, Branch * a_branch, PartitionVars * a_parVars) protected inherited
Position Boundary::getCenter () const inherited
Returns the center of the boundary.
Definition at line 106 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, and SUMOReal.
Referenced by GUISUMOAbstractView::centerTo(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), GUIVehicle::setFunctionalColor(), and GUIDanielPerspectiveChanger::zoom().
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::GetFirst (Iterator & a_it) inline inherited
Get 'first' for iteration.
Definition at line 246 of file RTree.h.
SUMOReal Boundary::getHeight () const inherited
Returns the height of the boundary.
Definition at line 142 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getPositionInformation(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), and GUIPerspectiveChanger::patchedViewPort().
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::GetNext (Iterator & a_it) inline inherited
Get Next for iteration.
Definition at line 257 of file RTree.h.
SUMOReal Boundary::getWidth () const inherited
Returns the width of the boudary.
Definition at line 136 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::getPositionInformation(), GUIDanielPerspectiveChanger::getZoom(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::p2m(), and GUIPerspectiveChanger::patchedViewPort().
Boundary & Boundary::grow (SUMOReal by) inherited
extends the boundary by the given amount
The method returns a reference to the instance for further use
Definition at line 200 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), traci::TraCIServer::collectObjectsInRange(), GUIEdge::getBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUILaneSpeedTrigger::getCenteringBoundary(), GUICalibrator::getCenteringBoundary(), GUIInstantInductLoop::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::getCenteringBoundary(), GUIJunctionWrapper::getCenteringBoundary(), GUIE3Collector::MyWrapper::getCenteringBoundary(), GUIVehicle::getCenteringBoundary(), GUIBusStop::getCenteringBoundary(), GUI_E2_ZS_Collector::MyWrapper::getCenteringBoundary(), GUIEdge::getCenteringBoundary(), GUITriggeredRerouter::GUITriggeredRerouterEdge::getCenteringBoundary(), GUIInductLoop::MyWrapper::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), TraCIServerAPI_Lane::getTree(), NBEdgeCont::ignoreFilterMatch(), and GUINet::initGUIStructures().
void Boundary::growHeight (SUMOReal by) inherited
Definition at line 216 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void Boundary::growWidth (SUMOReal by) inherited
Definition at line 209 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::InitNode (Node * a_node) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::InitParVars (PartitionVars * a_parVars, int a_maxRects, int a_minFill) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::InitRect (Rect * a_rect) protected inherited
virtual void SUMORTree::Insert (const float a_min[2], const float a_max[2], GUIGlObject * a_dataId) inline virtual
Insert entry.
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
See Also
RTree::Insert
Reimplemented in LayeredRTree.
Definition at line 81 of file SUMORTree.h.
References RTree< DATATYPE, DATATYPENP, ELEMTYPE, NUMDIMS, CONTEXT, ELEMTYPEREAL, TMAXNODES, TMINNODES >::Insert(), and myLock.
Referenced by addAdditionalGLObject().
virtual void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Insert (const float a_min[NUMDIMS], const float a_max[NUMDIMS], const GUIGlObject * & a_dataId) virtual inherited
Insert entry
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::InsertRect (Rect * a_rect, const GUIGlObject * & a_id, Node ** a_root, int a_level) protected inherited
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::InsertRectRec (Rect * a_rect, const GUIGlObject * & a_id, Node * a_node, Node ** a_newNode, int a_level) protected inherited
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::IsNull (Iterator & a_it) inline inherited
Is iterator NULL, or at end?
Definition at line 260 of file RTree.h.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::LoadNodes (Node * a_nodeA, Node * a_nodeB, PartitionVars * a_parVars) protected inherited
void Boundary::moveby (SUMOReal x, SUMOReal y) inherited
Moves the boundary by the given amount.
Definition at line 249 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::move(), and GeoConvHelper::moveConvertedBy().
Rect RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::NodeCover (Node * a_node) protected inherited
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Overlap (Rect * a_rectA, Rect * a_rectB) protected inherited
bool Boundary::overlapsWith (const AbstractPoly & poly, SUMOReal offset = 0) const virtual inherited
Returns whether the boundary overlaps with the given polygon.
Implements AbstractPoly.
Definition at line 156 of file Boundary.cpp.
References AbstractPoly::crosses(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, AbstractPoly::partialWithin(), and Boundary::partialWithin().
Referenced by NIVissimBoundedClusterObject::crosses(), NBEdgeCont::ignoreFilterMatch(), NIVissimConnectionCluster::overlapsWith(), and NIVissimConnectionCluster::NodeSubCluster::overlapsWith().
bool Boundary::partialWithin (const AbstractPoly & poly, SUMOReal offset = 0) const virtual inherited
Returns whether the boundary is partially within the given polygon.
Implements AbstractPoly.
Definition at line 190 of file Boundary.cpp.
References AbstractPoly::around(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by PCPolyContainer::insert(), and Boundary::overlapsWith().
int RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::PickBranch (Rect * a_rect, Node * a_node) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::PickSeeds (PartitionVars * a_parVars) protected inherited
float RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RectSphericalVolume (Rect * a_rect) protected inherited
float RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RectVolume (Rect * a_rect) protected inherited
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::ReInsert (Node * a_node, ListNode ** a_listNode) protected inherited
virtual void SUMORTree::Remove (const float a_min[2], const float a_max[2], GUIGlObject * a_dataId) inline virtual
Remove entry.
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
See Also
RTree::Remove
Reimplemented in LayeredRTree.
Definition at line 93 of file SUMORTree.h.
References myLock, and RTree< DATATYPE, DATATYPENP, ELEMTYPE, NUMDIMS, CONTEXT, ELEMTYPEREAL, TMAXNODES, TMINNODES >::Remove().
Referenced by removeAdditionalGLObject().
virtual void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Remove (const float a_min[NUMDIMS], const float a_max[NUMDIMS], const GUIGlObject * & a_dataId) virtual inherited
Remove entry
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
void SUMORTree::removeAdditionalGLObject (GUIGlObject * o) inline
Removes an additional object (detector/shape/trigger) from being visualised.
Parameters
[in] o The object to remove
Definition at line 128 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), Remove(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIShapeContainer::movePOI(), GUIShapeContainer::removePOI(), GUIShapeContainer::removePolygon(), and GUIShapeContainer::reshapePolygon().
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RemoveAll () inherited
DK 15.10.2008 - end.
Remove all entries from tree
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RemoveAllRec (Node * a_node) protected inherited
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RemoveRect (Rect * a_rect, const GUIGlObject * & a_id, Node ** a_root) protected inherited
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::RemoveRectRec (Rect * a_rect, const GUIGlObject * & a_id, Node * a_node, ListNode ** a_listNode) protected inherited
void Boundary::reset () inherited
Resets the boundary.
Definition at line 66 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Reset () protected inherited
virtual int RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Search (const float a_min[NUMDIMS], const float a_max[NUMDIMS], const GUIVisualizationSettings & c) virtual inherited
DK 15.10.2008 - begin.
Find all within search rectangle
Parameters
a_min Min of search bounding rect
a_max Max of search bounding rect
a_searchResult Search result array. Caller should set grow size. Function will reset, not append to array.
a_resultCallback Callback function to return result. Callback should return 'true' to continue searching
a_context User context to pass as parameter to a_resultCallback
Returns
Returns the number of entries found
virtual int SUMORTree::Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings & c) inline virtual
Find all within search rectangle.
Parameters
a_min Min of search bounding rect
a_max Max of search bounding rect
a_searchResult Search result array. Caller should set grow size. Function will reset, not append to array.
a_resultCallback Callback function to return result. Callback should return 'true' to continue searching
a_context User context to pass as parameter to a_resultCallback
Returns
Returns the number of entries found
See Also
RTree::Search
Reimplemented in LayeredRTree.
Definition at line 108 of file SUMORTree.h.
References myLock, and RTree< DATATYPE, DATATYPENP, ELEMTYPE, NUMDIMS, CONTEXT, ELEMTYPEREAL, TMAXNODES, TMINNODES >::Search().
Referenced by GUIViewTraffic::doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
bool RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::Search (Node * a_node, Rect * a_rect, int & a_foundCount, const GUIVisualizationSettings & c) protected inherited
void Boundary::set (SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax) inherited
Sets the boundary to the given values.
Definition at line 240 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by traci::TraCIServer::readTypeCheckingBoundary().
void RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::SplitNode (Node * a_node, Branch * a_branch, Node ** a_newNode) protected inherited
SUMOReal Boundary::xmax () const inherited
Returns maximum x-coordinate.
Definition at line 118 of file Boundary.cpp.
References Boundary::myXmax.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), addAdditionalGLObject(), TraCIRTree::addObject(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvassLeft(), traci::TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_GUI::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), removeAdditionalGLObject(), TraCIRTree::removeAdditionalGLObject(), Boundary::set(), GUIVehicle::setFunctionalColor(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::xmin () const inherited
Returns minimum x-coordinate.
Definition at line 112 of file Boundary.cpp.
References Boundary::myXmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), addAdditionalGLObject(), TraCIRTree::addObject(), GUISUMOAbstractView::applyGLTransform(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvassLeft(), traci::TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), GUISUMOAbstractView::getPositionInformation(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_GUI::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), removeAdditionalGLObject(), TraCIRTree::removeAdditionalGLObject(), Boundary::set(), GUIVehicle::setFunctionalColor(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::ymax () const inherited
Returns maximum y-coordinate.
Definition at line 130 of file Boundary.cpp.
References Boundary::myYmax.
Referenced by Boundary::add(), addAdditionalGLObject(), TraCIRTree::addObject(), GUIDanielPerspectiveChanger::changeCanvassLeft(), traci::TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_GUI::processGet(), removeAdditionalGLObject(), TraCIRTree::removeAdditionalGLObject(), Boundary::set(), GUIVehicle::setFunctionalColor(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::ymin () const inherited
Returns minimum y-coordinate.
Definition at line 124 of file Boundary.cpp.
References Boundary::myYmin.
Referenced by Boundary::add(), addAdditionalGLObject(), TraCIRTree::addObject(), GUISUMOAbstractView::applyGLTransform(), GUIDanielPerspectiveChanger::changeCanvassLeft(), traci::TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GUISUMOAbstractView::getPositionInformation(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_GUI::processGet(), removeAdditionalGLObject(), TraCIRTree::removeAdditionalGLObject(), Boundary::set(), GUIVehicle::setFunctionalColor(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
Field Documentation
Node* RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::m_root protected inherited
Root of tree.
Definition at line 359 of file RTree.h.
float RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::m_unitSphereVolume protected inherited
Unit sphere constant for required number of dimensions.
Definition at line 360 of file RTree.h.
MFXMutex SUMORTree::myLock protected
A mutex avoiding parallel change and traversal of the tree.
Definition at line 138 of file SUMORTree.h.
Referenced by Insert(), Remove(), and Search().
Operation RTree< GUIGlObject * , GUIGlObject , float , NUMDIMS, GUIVisualizationSettings , float , 8 , 8 / 2 >::myOperation protected inherited
Definition at line 361 of file RTree.h.
The documentation for this class was generated from the following file:
SUMORTree.h