SUMO - Simulation of Urban MObility: MSPerson::MSPersonStage_Waiting Class Reference
MSPerson::MSPersonStage_Waiting Class Reference
#include <MSPerson.h>
Public Member Functions
virtual void beginEventOutput (const MSPerson &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSPerson &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
SUMOReal getAngle (SUMOTime now) const
const MSEdge & getDestination () const
returns the destination edge
const MSEdge * getEdge (SUMOTime now) const
Returns the current edge.
SUMOReal getEdgeAngle (const MSEdge *e, SUMOReal at) const
SUMOReal getEdgePos (SUMOTime now) const
Position getEdgePosition (const MSEdge *e, SUMOReal at, SUMOReal offset) const
get position on edge e at length at with orthogonal offset
const MSEdge * getFromEdge () const
Position getPosition (SUMOTime now) const
StageType getStageType () const
std::string getStageTypeName () const
return string representation of the current stage
SUMOTime getUntil () const
virtual bool isWaiting4Vehicle () const
Whether the person waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the person waits for a vehicle of the line specified.
MSPersonStage_Waiting (const MSEdge &destination, SUMOTime duration, SUMOTime until, SUMOReal pos, const std::string &actType)
constructor
virtual void proceed (MSNet *net, MSPerson *person, SUMOTime now, MSEdge *previousEdge, const SUMOReal at)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual SUMOTime timeWaiting4Vehicle (SUMOTime) const
the time this person spent waiting for a vehicle
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
~MSPersonStage_Waiting ()
destructor
Protected Attributes
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach (either by walking or driving)
StageType myType
The type of this stage.
Private Member Functions
MSPersonStage_Waiting (const MSPersonStage_Waiting &)
Invalidated copy constructor.
MSPersonStage_Waiting & operator= (const MSPersonStage_Waiting &)
Invalidated assignment operator.
Private Attributes
std::string myActType
The type of activity.
SUMOReal myStartPos
SUMOTime myWaitingDuration
the time the person is waiting
SUMOTime myWaitingUntil
the time until the person is waiting
Detailed Description
A "real" stage performing a waiting over the specified time
Definition at line 398 of file MSPerson.h.
Constructor & Destructor Documentation
MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting (const MSEdge & destination, SUMOTime duration, SUMOTime until, SUMOReal pos, const std::string & actType)
constructor
Definition at line 432 of file MSPerson.cpp.
References Named::getID(), MSEdge::getLength(), SUMOVehicleParameter::interpretEdgePos(), MSPerson::MSPersonStage::myDestination, myStartPos, and SUMO_ATTR_DEPARTPOS.
MSPerson::MSPersonStage_Waiting::~MSPersonStage_Waiting ()
destructor
Definition at line 444 of file MSPerson.cpp.
MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting (const MSPersonStage_Waiting &) private
Invalidated copy constructor.
Member Function Documentation
void MSPerson::MSPersonStage_Waiting::beginEventOutput (const MSPerson & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSPerson::MSPersonStage.
Definition at line 514 of file MSPerson.cpp.
References MSPerson::getEdge(), Named::getID(), MSPerson::getID(), OutputDevice::openTag(), and time2string().
void MSPerson::MSPersonStage_Waiting::endEventOutput (const MSPerson & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSPerson::MSPersonStage.
Definition at line 525 of file MSPerson.cpp.
References MSPerson::getEdge(), Named::getID(), MSPerson::getID(), OutputDevice::openTag(), and time2string().
SUMOReal MSPerson::MSPersonStage_Waiting::getAngle (SUMOTime now) const virtual
Implements MSPerson::MSPersonStage.
Definition at line 478 of file MSPerson.cpp.
const MSEdge & MSPerson::MSPersonStage::getDestination () const inherited
returns the destination edge
Definition at line 70 of file MSPerson.cpp.
const MSEdge * MSPerson::MSPersonStage_Waiting::getEdge (SUMOTime now) const virtual
Returns the current edge.
Implements MSPerson::MSPersonStage.
Definition at line 448 of file MSPerson.cpp.
SUMOReal MSPerson::MSPersonStage::getEdgeAngle (const MSEdge * e, SUMOReal at) const inherited
Definition at line 106 of file MSPerson.cpp.
References MSEdge::getLanes(), and PositionVector::rotationDegreeAtOffset().
SUMOReal MSPerson::MSPersonStage_Waiting::getEdgePos (SUMOTime now) const virtual
Implements MSPerson::MSPersonStage.
Definition at line 460 of file MSPerson.cpp.
Position MSPerson::MSPersonStage::getEdgePosition (const MSEdge * e, SUMOReal at, SUMOReal offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 96 of file MSPerson.cpp.
References MSEdge::getLanes(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), PositionVector::move2side(), and PositionVector::positionAtOffset().
const MSEdge * MSPerson::MSPersonStage_Waiting::getFromEdge () const virtual
Implements MSPerson::MSPersonStage.
Definition at line 454 of file MSPerson.cpp.
Position MSPerson::MSPersonStage_Waiting::getPosition (SUMOTime now) const virtual
Implements MSPerson::MSPersonStage.
Definition at line 472 of file MSPerson.cpp.
References MSPerson::SIDEWALK_OFFSET.
StageType MSPerson::MSPersonStage::getStageType () const inline inherited
Definition at line 100 of file MSPerson.h.
References MSPerson::MSPersonStage::myType.
std::string MSPerson::MSPersonStage_Waiting::getStageTypeName () const inline virtual
return string representation of the current stage
Implements MSPerson::MSPersonStage.
Definition at line 418 of file MSPerson.h.
References myActType.
SUMOTime MSPerson::MSPersonStage_Waiting::getUntil () const
Definition at line 466 of file MSPerson.cpp.
Referenced by MSPerson::routeOutput().
virtual bool MSPerson::MSPersonStage::isWaiting4Vehicle () const inline virtual inherited
Whether the person waits for a vehicle.
Reimplemented in MSPerson::MSPersonStage_Driving.
Definition at line 120 of file MSPerson.h.
bool MSPerson::MSPersonStage::isWaitingFor (const std::string & line) const virtual inherited
Whether the person waits for a vehicle of the line specified.
Reimplemented in MSPerson::MSPersonStage_Driving.
Definition at line 90 of file MSPerson.cpp.
MSPersonStage_Waiting& MSPerson::MSPersonStage_Waiting::operator= (const MSPersonStage_Waiting &) private
Invalidated assignment operator.
void MSPerson::MSPersonStage_Waiting::proceed (MSNet * net, MSPerson * person, SUMOTime now, MSEdge * previousEdge, const SUMOReal at) virtual
proceeds to the next step
Implements MSPerson::MSPersonStage.
Definition at line 484 of file MSPerson.cpp.
References MSEdge::addPerson(), MSNet::getPersonControl(), MAX3(), and MSPersonControl::setWaitEnd().
void MSPerson::MSPersonStage_Waiting::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSPerson::MSPersonStage.
Definition at line 501 of file MSPerson.cpp.
References OutputDevice::closeTag(), MSPerson::getDestination(), MSPerson::getID(), OutputDevice::openTag(), SUMO_ATTR_DURATION, SUMO_ATTR_LANE, SUMO_ATTR_UNTIL, time2string(), and OutputDevice::writeAttr().
void MSPerson::MSPersonStage::setArrived (SUMOTime now) inherited
logs end of the step
Definition at line 84 of file MSPerson.cpp.
void MSPerson::MSPersonStage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 76 of file MSPerson.cpp.
virtual SUMOTime MSPerson::MSPersonStage::timeWaiting4Vehicle (SUMOTime) const inline virtual inherited
the time this person spent waiting for a vehicle
Reimplemented in MSPerson::MSPersonStage_Driving.
Definition at line 125 of file MSPerson.h.
void MSPerson::MSPersonStage_Waiting::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSPerson::MSPersonStage.
Definition at line 493 of file MSPerson.cpp.
References OutputDevice::openTag(), and time2string().
Field Documentation
std::string MSPerson::MSPersonStage_Waiting::myActType private
The type of activity.
Definition at line 459 of file MSPerson.h.
Referenced by getStageTypeName().
SUMOTime MSPerson::MSPersonStage::myArrived protected inherited
the time at which this stage ended
Definition at line 167 of file MSPerson.h.
SUMOTime MSPerson::MSPersonStage::myDeparted protected inherited
the time at which this stage started
Definition at line 164 of file MSPerson.h.
const MSEdge& MSPerson::MSPersonStage::myDestination protected inherited
the next edge to reach (either by walking or driving)
Definition at line 161 of file MSPerson.h.
Referenced by MSPersonStage_Waiting().
SUMOReal MSPerson::MSPersonStage_Waiting::myStartPos private
Definition at line 461 of file MSPerson.h.
Referenced by MSPersonStage_Waiting().
StageType MSPerson::MSPersonStage::myType protected inherited
The type of this stage.
Definition at line 170 of file MSPerson.h.
Referenced by MSPerson::MSPersonStage::getStageType().
SUMOTime MSPerson::MSPersonStage_Waiting::myWaitingDuration private
the time the person is waiting
Definition at line 453 of file MSPerson.h.
SUMOTime MSPerson::MSPersonStage_Waiting::myWaitingUntil private
the time until the person is waiting
Definition at line 456 of file MSPerson.h.
The documentation for this class was generated from the following files:
MSPerson.h
MSPerson.cpp