SUMO - Simulation of Urban MObility: AGTrip Class Reference
AGTrip Class Reference
#include <AGTrip.h>
Public Member Functions
void addLayOver (AGPosition by)
void addLayOver (AGTrip &trip)
void addLayOverWithoutDestination (AGTrip &trip)
AGTrip (AGPosition from, AGPosition to, int at)
AGTrip (AGPosition from, AGPosition to, AGCar c, int at)
AGTrip (AGPosition from, AGPosition to, AGBus b, int at)
AGTrip (AGPosition from, AGPosition to, std::string v, int at)
AGTrip (AGPosition from, AGPosition to, std::string v, int at, int day)
int estimateDepTime (int arrTime, SUMOReal secPerKm)
AGPosition getArr ()
int getArrTime (SUMOReal secPerKm)
int getDay ()
AGPosition getDep ()
std::list< AGPosition > * getPassed ()
int getRideBackArrTime (SUMOReal secPerKm)
int getTime ()
int getTimeTrip (SUMOReal secPerKm)
std::string getType ()
std::string getVehicleName ()
bool isDaily ()
bool operator< (AGTrip &trip)
void print ()
void setArr (AGPosition arrival)
void setDay (int day)
void setDep (AGPosition departure)
void setDepTime (int time)
void setType (std::string type)
void setVehicleName (std::string name)
Private Attributes
int myDay
int myDepTime
AGPosition myFrom
std::list< AGPosition > myPassBy
AGPosition myTo
std::string myType
std::string myVehicle
Detailed Description
Definition at line 46 of file AGTrip.h.
Constructor & Destructor Documentation
AGTrip::AGTrip (AGPosition from, AGPosition to, int at) inline
Definition at line 48 of file AGTrip.h.
AGTrip::AGTrip (AGPosition from, AGPosition to, AGCar c, int at) inline
Definition at line 54 of file AGTrip.h.
AGTrip::AGTrip (AGPosition from, AGPosition to, AGBus b, int at) inline
Definition at line 61 of file AGTrip.h.
AGTrip::AGTrip (AGPosition from, AGPosition to, std::string v, int at) inline
Definition at line 68 of file AGTrip.h.
AGTrip::AGTrip (AGPosition from, AGPosition to, std::string v, int at, int day) inline
Definition at line 75 of file AGTrip.h.
Member Function Documentation
void AGTrip::addLayOver (AGPosition by)
Definition at line 66 of file AGTrip.cpp.
References myPassBy.
Referenced by AGActivities::generateBusTraffic().
void AGTrip::addLayOver (AGTrip & trip)
Definition at line 71 of file AGTrip.cpp.
References myPassBy, and myTo.
void AGTrip::addLayOverWithoutDestination (AGTrip & trip)
Definition at line 80 of file AGTrip.cpp.
References myPassBy.
int AGTrip::estimateDepTime (int arrTime, SUMOReal secPerKm)
estimate the departure time needed for a given arrival time and a speed in seconds per kilometer
Definition at line 157 of file AGTrip.cpp.
References getTimeTrip().
AGPosition AGTrip::getArr ()
Definition at line 108 of file AGTrip.cpp.
References myTo.
Referenced by AGActivityTripWriter::addTrip().
int AGTrip::getArrTime (SUMOReal secPerKm)
returns the estimated arrival time given the time to make one kilometer
Definition at line 142 of file AGTrip.cpp.
References getTimeTrip(), and myDepTime.
Referenced by getRideBackArrTime().
int AGTrip::getDay ()
Definition at line 187 of file AGTrip.cpp.
References myDay.
Referenced by AGActivityTripWriter::addTrip(), operator<(), AGActivityGen::timeTripValidation(), and AGActivityGen::varDepTime().
AGPosition AGTrip::getDep ()
Definition at line 103 of file AGTrip.cpp.
References myFrom.
Referenced by AGActivityTripWriter::addTrip().
std::list< AGPosition > * AGTrip::getPassed ()
Definition at line 88 of file AGTrip.cpp.
References myPassBy.
Referenced by AGActivityTripWriter::addTrip().
int AGTrip::getRideBackArrTime (SUMOReal secPerKm)
returns the time regarding the departure time going through the different points and coming back to the initial position given the time to make one kilometer
Definition at line 147 of file AGTrip.cpp.
References AGPosition::distanceTo(), getArrTime(), myFrom, and myTo.
int AGTrip::getTime ()
Definition at line 113 of file AGTrip.cpp.
References myDepTime.
Referenced by AGActivityTripWriter::addTrip(), operator<(), AGActivityGen::timeTripValidation(), and AGActivityGen::varDepTime().
int AGTrip::getTimeTrip (SUMOReal secPerKm)
gives the time in seconds for the trip given a speed in seconds per kilometer (in city, not car speed but time needed to make a distance in the city)
Definition at line 118 of file AGTrip.cpp.
References AGPosition::distanceTo(), myFrom, myPassBy, myTo, and SUMOReal.
Referenced by estimateDepTime(), and getArrTime().
std::string AGTrip::getType ()
Definition at line 93 of file AGTrip.cpp.
References myType.
Referenced by AGActivityTripWriter::addTrip(), and AGActivityGen::varDepTime().
std::string AGTrip::getVehicleName ()
Definition at line 162 of file AGTrip.cpp.
References myVehicle.
Referenced by AGActivityTripWriter::addTrip().
bool AGTrip::isDaily ()
returns whether this is a daily trip or a one day trip
Definition at line 182 of file AGTrip.cpp.
References myDay.
bool AGTrip::operator< (AGTrip & trip)
Definition at line 42 of file AGTrip.cpp.
References getDay(), and getTime().
void AGTrip::print ()
Definition at line 54 of file AGTrip.cpp.
References myDay, myDepTime, myFrom, myTo, myType, myVehicle, and AGPosition::print().
void AGTrip::setArr (AGPosition arrival)
Definition at line 172 of file AGTrip.cpp.
References AGPosition::getPosition(), AGPosition::getStreet(), and myTo.
void AGTrip::setDay (int day)
Definition at line 192 of file AGTrip.cpp.
References myDay.
Referenced by AGActivityGen::varDepTime().
void AGTrip::setDep (AGPosition departure)
Definition at line 177 of file AGTrip.cpp.
References AGPosition::getPosition(), AGPosition::getStreet(), and myFrom.
void AGTrip::setDepTime (int time)
Definition at line 152 of file AGTrip.cpp.
References myDepTime.
Referenced by AGActivities::generateInOutTraffic(), and AGActivityGen::varDepTime().
void AGTrip::setType (std::string type)
Definition at line 98 of file AGTrip.cpp.
References myType.
Referenced by AGActivities::generateRandomTraffic(), and AGActivityGen::makeActivityTrips().
void AGTrip::setVehicleName (std::string name)
Definition at line 167 of file AGTrip.cpp.
References myVehicle.
Field Documentation
int AGTrip::myDay private
if everyday : 0 else : number of the day (!= 0)
Definition at line 144 of file AGTrip.h.
Referenced by getDay(), isDaily(), print(), and setDay().
int AGTrip::myDepTime private
Definition at line 133 of file AGTrip.h.
Referenced by getArrTime(), getTime(), print(), and setDepTime().
AGPosition AGTrip::myFrom private
Definition at line 131 of file AGTrip.h.
Referenced by getDep(), getRideBackArrTime(), getTimeTrip(), print(), and setDep().
std::list<AGPosition> AGTrip::myPassBy private
Definition at line 145 of file AGTrip.h.
Referenced by addLayOver(), addLayOverWithoutDestination(), getPassed(), and getTimeTrip().
AGPosition AGTrip::myTo private
Definition at line 132 of file AGTrip.h.
Referenced by addLayOver(), getArr(), getRideBackArrTime(), getTimeTrip(), print(), and setArr().
std::string AGTrip::myType private
indicates if it is a bus or a car (or any type) "bus", "default" or "random" (which is a kind of default)
Definition at line 139 of file AGTrip.h.
Referenced by getType(), print(), and setType().
std::string AGTrip::myVehicle private
Definition at line 134 of file AGTrip.h.
Referenced by getVehicleName(), print(), and setVehicleName().
The documentation for this class was generated from the following files:
AGTrip.h
AGTrip.cpp