SUMO - Simulation of Urban MObility: MSVehicleType Class Reference
MSVehicleType Class Reference
The car-following model and parameter.
#include <MSVehicleType.h>
Public Member Functions
bool amVehicleSpecific () const
Returns whether this type belongs to a single vehicle only (was modified)
const SUMOVTypeParameter & getParameter () const
MSVehicleType (const SUMOVTypeParameter &parameter)
Constructor.
bool wasSet (int what) const
Returns whether the given parameter was set.
virtual ~MSVehicleType ()
Destructor.
Atomar getter for simulation
const std::string & getID () const
Returns the name of the vehicle type.
SUMOReal getLength () const
Get vehicle's length [m].
SUMOReal getLengthWithGap () const
Get vehicle's length including the minimum gap [m].
SUMOReal getMinGap () const
Get the free space in front of vehicles of this class.
const MSCFModel & getCarFollowModel () const
Returns the vehicle type's car following model definition (const version)
MSCFModel & getCarFollowModel ()
Returns the vehicle type's car following model definition (non-const version)
SUMOReal getMaxSpeed () const
Get vehicle's maximum speed [m/s].
SUMOReal computeChosenSpeedDeviation (MTRand &rng) const
Computes and returns the speed deviation.
SUMOReal getDefaultProbability () const
Get the default probability of this vehicle type.
SUMOVehicleClass getVehicleClass () const
Get this vehicle type's vehicle class.
SUMOEmissionClass getEmissionClass () const
Get this vehicle type's emission class.
const RGBColor & getColor () const
Returns this type's color.
SUMOReal getSpeedFactor () const
Returns this type's speed factor.
SUMOReal getSpeedDeviation () const
Returns this type's speed deviation.
SUMOReal getImpatience () const
Returns this type's impatience.
Atomar getter for visualization
SUMOReal getWidth () const
Get the width which vehicles of this class shall have when being drawn.
SUMOReal getHeight () const
Get the height which vehicles of this class shall have when being drawn.
SUMOVehicleShape getGuiShape () const
Get this vehicle type's shape.
std::string getOSGFile () const
Get this vehicle type's 3D model file name.
std::string getImgFile () const
Get this vehicle type's raster model file name.
Setter methods
void setLength (const SUMOReal &length)
Set a new value for this type's length.
void setMinGap (const SUMOReal &minGap)
Set a new value for this type's minimum gap.
void setMaxSpeed (const SUMOReal &maxSpeed)
Set a new value for this type's maximum speed.
void setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
void setDefaultProbability (const SUMOReal &prob)
Set a new value for this type's default probability.
void setSpeedFactor (const SUMOReal &factor)
Set a new value for this type's speed factor.
void setSpeedDeviation (const SUMOReal &dev)
Set a new value for this type's speed deviation.
void setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
void setColor (const RGBColor &color)
Set a new value for this type's color.
void setWidth (const SUMOReal &width)
Set a new value for this type's width.
void setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
void setImpatience (const SUMOReal impatience)
Set a new value for this type's impatience.
Static Public Member Functions
Static methods for building vehicle types
static MSVehicleType * build (SUMOVTypeParameter &from)
Builds the microsim vehicle type described by the given parameter.
static MSVehicleType * build (const std::string &id, const MSVehicleType *from)
Duplicates the microsim vehicle type giving it a the given id.
Private Member Functions
MSVehicleType (const MSVehicleType &)
Invalidated copy constructor.
MSVehicleType & operator= (const MSVehicleType &)
Invalidated assignment operator.
Private Attributes
MSCFModel * myCarFollowModel
ID of the car following model.
const MSVehicleType * myOriginalType
The original type.
SUMOVTypeParameter myParameter
the parameter container
Detailed Description
The car-following model and parameter.
MSVehicleType stores the parameter of a single vehicle type and methods that use these for computing the vehicle's car-following behavior
It is assumed that within the simulation many vehicles are using the same vehicle type, quite common is using only one vehicle type for all vehicles.
You can think of it like of having a vehicle type for each VW Golf or Ford Mustang in your simulation while the car instances just refer to it.
Definition at line 74 of file MSVehicleType.h.
Constructor & Destructor Documentation
MSVehicleType::MSVehicleType (const SUMOVTypeParameter & parameter)
Constructor.
Parameters
[in] parameter The vehicle type's parameter
Definition at line 60 of file MSVehicleType.cpp.
References getLength(), and getMaxSpeed().
Referenced by build().
MSVehicleType::~MSVehicleType () virtual
Destructor.
Definition at line 67 of file MSVehicleType.cpp.
References myCarFollowModel.
MSVehicleType::MSVehicleType (const MSVehicleType &) private
Invalidated copy constructor.
Member Function Documentation
bool MSVehicleType::amVehicleSpecific () const inline
Returns whether this type belongs to a single vehicle only (was modified)
Returns
Whether this vehicle type is based on a differen one, and belongs to one vehicle only
Definition at line 392 of file MSVehicleType.h.
References myOriginalType.
Referenced by MSVehicle::replaceVehicleType(), and MSVehicle::~MSVehicle().
MSVehicleType * MSVehicleType::build (SUMOVTypeParameter & from) static
Builds the microsim vehicle type described by the given parameter.
Parameters
[in] from The vehicle type description
Returns
The built vehicle type
Exceptions
ProcessError on false values (not et used)
Definition at line 190 of file MSVehicleType.cpp.
References SUMOVTypeParameter::cfModel, DEFAULT_VEH_ACCEL, DEFAULT_VEH_DECEL, DEFAULT_VEH_SIGMA, DEFAULT_VEH_TAU, DEFAULT_VEH_TMP1, DEFAULT_VEH_TMP2, DEFAULT_VEH_TMP3, DEFAULT_VEH_TMP4, DEFAULT_VEH_TMP5, SUMOVTypeParameter::get(), MSVehicleType(), myCarFollowModel, SUMO_ATTR_ACCEL, SUMO_ATTR_CF_IDM_DELTA, SUMO_ATTR_CF_IDM_STEPPING, SUMO_ATTR_CF_IDMM_ADAPT_FACTOR, SUMO_ATTR_CF_IDMM_ADAPT_TIME, SUMO_ATTR_CF_KERNER_PHI, SUMO_ATTR_CF_PWAGNER2009_APPROB, SUMO_ATTR_CF_PWAGNER2009_TAULAST, SUMO_ATTR_CF_WIEDEMANN_ESTIMATION, SUMO_ATTR_CF_WIEDEMANN_SECURITY, SUMO_ATTR_DECEL, SUMO_ATTR_K, SUMO_ATTR_SIGMA, SUMO_ATTR_TAU, SUMO_ATTR_TMP1, SUMO_ATTR_TMP2, SUMO_ATTR_TMP3, SUMO_ATTR_TMP4, SUMO_ATTR_TMP5, SUMO_TAG_CF_BKERNER, SUMO_TAG_CF_DANIEL1, SUMO_TAG_CF_IDM, SUMO_TAG_CF_IDMM, SUMO_TAG_CF_KRAUSS, SUMO_TAG_CF_KRAUSS_ORIG1, SUMO_TAG_CF_KRAUSS_PLUS_SLOPE, SUMO_TAG_CF_PWAGNER2009, SUMO_TAG_CF_SMART_SK, and SUMO_TAG_CF_WIEDEMANN.
Referenced by TraCIServerAPI_Vehicle::getSingularType(), MSVehicleControl::MSVehicleControl(), MSRouteHandler::myEndElement(), and MSStateHandler::myStartElement().
MSVehicleType * MSVehicleType::build (const std::string & id, const MSVehicleType * from) static
Duplicates the microsim vehicle type giving it a the given id.
Parameters
[in] id The new id of the type
[in] from The vehicle type
Returns
The built vehicle type
Definition at line 288 of file MSVehicleType.cpp.
References MSCFModel::duplicate(), SUMOVTypeParameter::id, MSVehicleType(), myCarFollowModel, myOriginalType, and myParameter.
SUMOReal MSVehicleType::computeChosenSpeedDeviation (MTRand & rng) const
Computes and returns the speed deviation.
Returns
A new, random speed deviation
Definition at line 73 of file MSVehicleType.cpp.
References MAX2(), MIN2(), myParameter, RandHelper::randNorm(), SUMOVTypeParameter::speedDev, SUMOVTypeParameter::speedFactor, and SUMOReal.
Referenced by GUIVehicleControl::buildVehicle(), and MSVehicleControl::buildVehicle().
const MSCFModel& MSVehicleType::getCarFollowModel () const inline
Returns the vehicle type's car following model definition (const version)
Returns
The vehicle type's car following model definition
Definition at line 134 of file MSVehicleType.h.
References myCarFollowModel.
Referenced by MSVehicle::estimateLeaveSpeed(), MSVehicle::executeMove(), MSVehicle::getCarFollowModel(), TraCIServerAPI_VehicleType::getVariable(), MSVehicle::MSVehicle(), MSVehicle::planMoveInternal(), MSCalibrator::remainingVehicleCapacity(), TraCIServerAPI_VehicleType::setVariable(), and MSMeanData_HBEFA::MSLaneMeanDataValues::write().
MSCFModel& MSVehicleType::getCarFollowModel () inline
Returns the vehicle type's car following model definition (non-const version)
Returns
The vehicle type's car following model definition
Definition at line 142 of file MSVehicleType.h.
References myCarFollowModel.
const RGBColor& MSVehicleType::getColor () const inline
Returns this type's color.
Returns
The color of this type
Definition at line 190 of file MSVehicleType.h.
References SUMOVTypeParameter::color, and myParameter.
Referenced by TraCIServerAPI_VehicleType::getVariable().
SUMOReal MSVehicleType::getDefaultProbability () const inline
Get the default probability of this vehicle type.
Returns
The probability to use this type
Definition at line 164 of file MSVehicleType.h.
References SUMOVTypeParameter::defaultProbability, and myParameter.
Referenced by MSRouteHandler::myEndElement(), MSRouteHandler::openVehicleTypeDistribution(), and setDefaultProbability().
SUMOEmissionClass MSVehicleType::getEmissionClass () const inline
Get this vehicle type's emission class.
Returns
The emission class of this vehicle type
See Also
SUMOEmissionClass
Definition at line 182 of file MSVehicleType.h.
References SUMOVTypeParameter::emissionClass, and myParameter.
Referenced by MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHBEFA_CO2Emissions(), MSVehicle::getHBEFA_COEmissions(), MSVehicle::getHBEFA_FuelConsumption(), MSVehicle::getHBEFA_HCEmissions(), MSVehicle::getHBEFA_NOxEmissions(), MSVehicle::getHBEFA_PMxEmissions(), TraCIServerAPI_VehicleType::getVariable(), MSDevice_HBEFA::notifyMove(), MSMeanData_HBEFA::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSEmissionExport::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSFullExport::writeVehicles().
SUMOVehicleShape MSVehicleType::getGuiShape () const inline
Get this vehicle type's shape.
Returns
The shape of this vehicle type
See Also
SUMOVehicleShape
Definition at line 242 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::shape.
Referenced by GUIVehicle::drawAction_drawVehicleAsPoly(), and TraCIServerAPI_VehicleType::getVariable().
SUMOReal MSVehicleType::getHeight () const inline
Get the height which vehicles of this class shall have when being drawn.
Returns
The height of this type's vehicles
Definition at line 234 of file MSVehicleType.h.
References SUMOVTypeParameter::height, and myParameter.
const std::string& MSVehicleType::getID () const inline
Returns the name of the vehicle type.
Returns
This type's id
Definition at line 102 of file MSVehicleType.h.
References SUMOVTypeParameter::id, and myParameter.
Referenced by MSVehicleControl::addVType(), MSInductLoop::collectVehiclesOnDet(), MSVTypeProbe::execute(), MSDevice_Vehroutes::generateOutput(), MSDevice_Tripinfo::generateOutput(), GUIVehicle::getParameterWindow(), TraCIServerAPI_Vehicle::getSingularType(), MSInductLoop::leaveDetectorByMove(), MSVehicle::MSVehicle(), MSRouteHandler::myEndElement(), TraCIServerAPI_Vehicle::processGet(), MSBaseVehicle::saveState(), MSMeanData::MeanDataValues::vehicleApplies(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), and MSFullExport::writeVehicles().
std::string MSVehicleType::getImgFile () const inline
Get this vehicle type's raster model file name.
Returns
The raster file name of this vehicle type
Definition at line 257 of file MSVehicleType.h.
References SUMOVTypeParameter::imgFile, and myParameter.
Referenced by GUIPerson::drawAction_drawAsImage(), and GUIVehicle::drawAction_drawVehicleAsImage().
SUMOReal MSVehicleType::getImpatience () const inline
Returns this type's impatience.
Returns
The impatience of this type
Definition at line 214 of file MSVehicleType.h.
References SUMOVTypeParameter::impatience, and myParameter.
Referenced by setImpatience().
SUMOReal MSVehicleType::getLength () const inline
Get vehicle's length [m].
Returns
The length vehicles of this type have in m
Definition at line 110 of file MSVehicleType.h.
References SUMOVTypeParameter::length, and myParameter.
Referenced by MSCFModel_Wiedemann::_v(), MSInductLoop::collectVehiclesOnDet(), MSE2Collector::detectorUpdate(), GUIPerson::drawAction_drawAsImage(), drawAction_drawBlinker(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleAsImage(), GUIVehicle::drawAction_drawVehicleAsPoly(), GUIVehicle::drawAction_drawVehicleAsTrianglePlus(), drawAction_drawVehicleBrakeLight(), GUIVehicle::drawGL(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSLane::freeInsertion(), MSVehicle::getAngle(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealThisLeader(), TraCIServerAPI_VehicleType::getVariable(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSInductLoop::leaveDetectorByMove(), MSLane::maxSpeedGapInsertion(), MSLink::maybeOccupied(), MSVehicleType(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSVehicle::processNextStop(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), setLength(), and MSInstantInductLoop::write().
SUMOReal MSVehicleType::getLengthWithGap () const inline
Get vehicle's length including the minimum gap [m].
Returns
The length vehicles of this type have (including the minimum gap in m
Definition at line 118 of file MSVehicleType.h.
References SUMOVTypeParameter::length, SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSLaneChanger::change(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), GUIVehicle::drawGLAdditional(), MSLane::enteredByLaneChange(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::leftByLaneChange(), MSLane::maxSpeedGapInsertion(), MSVehicle::overlap(), MSLane::planMovements(), MSLaneChanger::registerUnchanged(), MSCalibrator::remainingVehicleCapacity(), MSLane::removeVehicle(), GUIVehicle::selectBlockingFoes(), MSLink::setApproaching(), MSLaneChanger::startChange(), MSLCM_DK2004::wantsChangeToLeft(), MSLCM_DK2004::wantsChangeToRight(), and MSQueueExport::writeLane().
SUMOReal MSVehicleType::getMaxSpeed () const inline
Get vehicle's maximum speed [m/s].
Returns
The maximum speed (in m/s) of vehicles of this class
Definition at line 150 of file MSVehicleType.h.
References SUMOVTypeParameter::maxSpeed, and myParameter.
Referenced by MSCFModel_IDM::desiredSpeed(), MSBaseVehicle::getMaxSpeed(), TraCIServerAPI_VehicleType::getVariable(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MSVehicle::MSVehicle(), MSVehicleType(), setMaxSpeed(), MSLCM_DK2004::wantsChangeToLeft(), MSLCM_DK2004::wantsChangeToRight(), and MSMeanData_HBEFA::MSLaneMeanDataValues::write().
SUMOReal MSVehicleType::getMinGap () const inline
Get the free space in front of vehicles of this class.
Returns
The place before the vehicle
Definition at line 126 of file MSVehicleType.h.
References SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSCFModel_IDM::_v(), GUIVehicle::drawGL(), MSLane::freeInsertion(), MSLane::getFollowerOnConsecutive(), MSBusStop::getLastFreePos(), MSLane::getLeaderOnConsecutive(), MSLane::getMissingRearGap(), MSLaneChanger::getRealLeader(), MSLaneChanger::getRealThisLeader(), TraCIServerAPI_VehicleType::getVariable(), MSLane::isInsertionSuccess(), MSLCM_DK2004::patchSpeed(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSVehicle::processNextStop(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), GUIVehicle::selectBlockingFoes(), setMinGap(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
std::string MSVehicleType::getOSGFile () const inline
Get this vehicle type's 3D model file name.
Returns
The model file name of this vehicle type
Definition at line 249 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::osgFile.
const SUMOVTypeParameter& MSVehicleType::getParameter () const inline
Definition at line 397 of file MSVehicleType.h.
References myParameter.
Referenced by MSDevice_Example::buildVehicleDevices().
SUMOReal MSVehicleType::getSpeedDeviation () const inline
Returns this type's speed deviation.
Returns
The speed deviation of this type
Definition at line 206 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::speedDev.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and setSpeedDeviation().
SUMOReal MSVehicleType::getSpeedFactor () const inline
Returns this type's speed factor.
Returns
The speed factor of this type
Definition at line 198 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::speedFactor.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and setSpeedFactor().
SUMOVehicleClass MSVehicleType::getVehicleClass () const inline
Get this vehicle type's vehicle class.
Returns
The class of this vehicle type
See Also
SUMOVehicleClass
Definition at line 173 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::vehicleClass.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicle::getBestLanes(), MSEdge::getDepartLane(), TraCIServerAPI_VehicleType::getVariable(), MSBaseVehicle::hasValidRoute(), MSEdge::prohibits(), and MSLane::succLinkSec().
SUMOReal MSVehicleType::getWidth () const inline
Get the width which vehicles of this class shall have when being drawn.
Returns
The width of this type's vehicles
Definition at line 227 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::width.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleAsImage(), GUIVehicle::drawAction_drawVehicleAsPoly(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), TraCIServerAPI_VehicleType::getVariable(), and setWidth().
MSVehicleType& MSVehicleType::operator= (const MSVehicleType &) private
Invalidated assignment operator.
void MSVehicleType::setColor (const RGBColor & color)
Set a new value for this type's color.
Parameters
[in] color The new color of this type
Definition at line 156 of file MSVehicleType.cpp.
References SUMOVTypeParameter::color, and myParameter.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setDefaultProbability (const SUMOReal & prob)
Set a new value for this type's default probability.
If the given value<0 then the one from the original type will be used.
Parameters
[in] prob The new default probability of this type
Definition at line 120 of file MSVehicleType.cpp.
References SUMOVTypeParameter::defaultProbability, getDefaultProbability(), myOriginalType, and myParameter.
void MSVehicleType::setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
Parameters
[in] eclass The new emission class of this type
Definition at line 150 of file MSVehicleType.cpp.
References SUMOVTypeParameter::emissionClass, and myParameter.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setImpatience (const SUMOReal impatience)
Set a new value for this type's impatience.
Parameters
[in] impatience The new impatience of this type
Definition at line 172 of file MSVehicleType.cpp.
References getImpatience(), SUMOVTypeParameter::impatience, myOriginalType, and myParameter.
void MSVehicleType::setLength (const SUMOReal & length)
Set a new value for this type's length.
If the given value<0 then the one from the original type will be used.
Parameters
[in] length The new length of this type
Definition at line 84 of file MSVehicleType.cpp.
References getLength(), SUMOVTypeParameter::length, myOriginalType, and myParameter.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMaxSpeed (const SUMOReal & maxSpeed)
Set a new value for this type's maximum speed.
If the given value<0 then the one from the original type will be used.
Parameters
[in] maxSpeed The new maximum speed of this type
Definition at line 104 of file MSVehicleType.cpp.
References getMaxSpeed(), SUMOVTypeParameter::maxSpeed, myOriginalType, and myParameter.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMinGap (const SUMOReal & minGap)
Set a new value for this type's minimum gap.
If the given value<0 then the one from the original type will be used.
Parameters
[in] offset The new minimum gap of this type
Definition at line 94 of file MSVehicleType.cpp.
References getMinGap(), SUMOVTypeParameter::minGap, myOriginalType, and myParameter.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
Parameters
[in] shape The new shape of this type
Definition at line 182 of file MSVehicleType.cpp.
References myParameter, and SUMOVTypeParameter::shape.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedDeviation (const SUMOReal & dev)
Set a new value for this type's speed deviation.
If the given value<0 then the one from the original type will be used.
Parameters
[in] dev The new speed deviation of this type
Definition at line 140 of file MSVehicleType.cpp.
References getSpeedDeviation(), myOriginalType, myParameter, and SUMOVTypeParameter::speedDev.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedFactor (const SUMOReal & factor)
Set a new value for this type's speed factor.
If the given value<0 then the one from the original type will be used.
Parameters
[in] factor The new speed factor of this type
Definition at line 130 of file MSVehicleType.cpp.
References getSpeedFactor(), myOriginalType, myParameter, and SUMOVTypeParameter::speedFactor.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
Parameters
[in] vclass The new vehicle class of this type
Definition at line 114 of file MSVehicleType.cpp.
References myParameter, and SUMOVTypeParameter::vehicleClass.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setWidth (const SUMOReal & width)
Set a new value for this type's width.
If the given value<0 then the one from the original type will be used.
Parameters
[in] width The new width of this type
Definition at line 162 of file MSVehicleType.cpp.
References getWidth(), myOriginalType, myParameter, and SUMOVTypeParameter::width.
Referenced by TraCIServerAPI_VehicleType::setVariable().
bool MSVehicleType::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 91 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::setParameter.
Field Documentation
MSCFModel* MSVehicleType::myCarFollowModel private
ID of the car following model.
Definition at line 407 of file MSVehicleType.h.
Referenced by build(), getCarFollowModel(), and ~MSVehicleType().
const MSVehicleType* MSVehicleType::myOriginalType private
The original type.
Definition at line 410 of file MSVehicleType.h.
Referenced by amVehicleSpecific(), build(), setDefaultProbability(), setImpatience(), setLength(), setMaxSpeed(), setMinGap(), setSpeedDeviation(), setSpeedFactor(), and setWidth().
SUMOVTypeParameter MSVehicleType::myParameter private
the parameter container
Definition at line 404 of file MSVehicleType.h.
Referenced by build(), computeChosenSpeedDeviation(), getColor(), getDefaultProbability(), getEmissionClass(), getGuiShape(), getHeight(), getID(), getImgFile(), getImpatience(), getLength(), getLengthWithGap(), getMaxSpeed(), getMinGap(), getOSGFile(), getParameter(), getSpeedDeviation(), getSpeedFactor(), getVehicleClass(), getWidth(), setColor(), setDefaultProbability(), setEmissionClass(), setImpatience(), setLength(), setMaxSpeed(), setMinGap(), setShape(), setSpeedDeviation(), setSpeedFactor(), setVClass(), setWidth(), and wasSet().
The documentation for this class was generated from the following files:
MSVehicleType.h
MSVehicleType.cpp