SUMO - Simulation of Urban MObility: MSLCM_DK2004 Class Reference
MSLCM_DK2004 Class Reference
A lane change model developed by D. Krajzewicz between 2004 and 2010.
#include <MSLCM_DK2004.h>
Public Member Functions
bool alreadyMoved () const
reset the flag whether a vehicle already moved to false
virtual void changed ()
void continueLaneChangeManeuver (bool moved)
void endLaneChangeManeuver ()
virtual void fulfillChangeRequest (MSVehicle::ChangeRequest request)
SUMOReal getChangeProbability () const
SUMOReal getLaneChangeCompletion () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
int getOwnState () const
SUMOReal getProb () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuouss lane change.
virtual void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isLaneChangeMidpointPassed () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
MSLCM_DK2004 (MSVehicle &v)
virtual SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
virtual void prepareStep ()
void removeLaneChangeShadow ()
remove the shadow copy of a lane change maneuver
virtual void requestLaneChange (MSVehicle::ChangeRequest request)
void resetMoved ()
reset the flag whether a vehicle already moved to false
void setOwnState (int state)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
virtual int wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked)
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked)
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual ~MSLCM_DK2004 ()
Protected Types
typedef std::pair< SUMOReal, int > Info
Protected Member Functions
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
bool currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
void informBlocker (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int &blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow)
virtual bool predInteraction (const MSVehicle *const leader)
Protected Attributes
bool myAlreadyMoved
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
SUMOReal myChangeProbability
MSVehicle::ChangeRequest myChangeRequest
bool myDontBrake
bool myHaveShadow
Wether a vehicle shadow exists.
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
bool myLaneChangeMidpointPassed
whether myLane has already been set to the target of the lane-change maneuver
SUMOTime myLastLaneChangeOffset
information how long ago the vehicle has performed a lane-change
SUMOReal myLeadingBlockerLength
SUMOReal myLeftSpace
int myOwnState
The current state of the vehicle.
MSLane * myShadowLane
The lane the vehicle shadow is on during a continuous lane change.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< SUMOReal > myVSafes
Detailed Description
A lane change model developed by D. Krajzewicz between 2004 and 2010.
Definition at line 64 of file MSLCM_DK2004.h.
Member Typedef Documentation
typedef std::pair<SUMOReal, int> MSLCM_DK2004::Info protected
Definition at line 142 of file MSLCM_DK2004.h.
Constructor & Destructor Documentation
MSLCM_DK2004::MSLCM_DK2004 (MSVehicle & v)
Definition at line 71 of file MSLCM_DK2004.cpp.
MSLCM_DK2004::~MSLCM_DK2004 () virtual
Definition at line 76 of file MSLCM_DK2004.cpp.
References changed().
Member Function Documentation
bool MSAbstractLaneChangeModel::alreadyMoved () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 265 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyMoved.
Referenced by MSLane::executeMovements().
bool MSLCM_DK2004::amBlockingFollower () inline protected
Definition at line 126 of file MSLCM_DK2004.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2004::amBlockingFollowerNB () inline protected
Definition at line 129 of file MSLCM_DK2004.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2004::amBlockingFollowerPlusNB () inline protected
Definition at line 132 of file MSLCM_DK2004.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2004::amBlockingLeader () inline protected
Definition at line 123 of file MSLCM_DK2004.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
void MSLCM_DK2004::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 614 of file MSLCM_DK2004.cpp.
References myChangeProbability, myDontBrake, MSAbstractLaneChangeModel::myLastLaneChangeOffset, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, and myVSafes.
Referenced by patchSpeed(), and ~MSLCM_DK2004().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 67 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
void MSAbstractLaneChangeModel::continueLaneChangeManeuver (bool moved) inherited
Definition at line 122 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), DELTA_T, MSEdge::EDGEFUNCTION_INTERNAL, MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::fixContinuations(), MSVehicle::fixPosition(), MSVehicle::getBestLanes(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSLane::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getParallelLane(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::leaveLane(), MSAbstractLaneChangeModel::myAlreadyMoved, MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLaneChangeMidpointPassed, MSAbstractLaneChangeModel::myLastLaneChangeOffset, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::removeLaneChangeShadow(), SUMOReal, time2string(), toString(), and WRITE_WARNING.
Referenced by MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSLCM_DK2004::currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 138 of file MSLCM_DK2004.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2004::currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 135 of file MSLCM_DK2004.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
void MSAbstractLaneChangeModel::endLaneChangeManeuver () inline inherited
Definition at line 286 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myShadowLane, and MSAbstractLaneChangeModel::removeLaneChangeShadow().
Referenced by MSVehicleTransfer::addVeh(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSLane::detectCollisions(), and MSVehicle::executeMove().
virtual void MSAbstractLaneChangeModel::fulfillChangeRequest (MSVehicle::ChangeRequest request) inline virtual inherited
Inform the model that a certain lane change request has been fulfilled by the lane changer, so the request won't be taken into account the next time.
Parameters
request indicates the request that was fulfilled
Definition at line 312 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myChangeRequest, and MSVehicle::REQUEST_NONE.
Referenced by MSLaneChanger::change().
SUMOReal MSLCM_DK2004::getChangeProbability () const inline
Definition at line 112 of file MSLCM_DK2004.h.
References myChangeProbability.
SUMOReal MSAbstractLaneChangeModel::getLaneChangeCompletion () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 250 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSVehicle::getAngle().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 260 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeDirection.
Referenced by MSVehicle::getAngle().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 239 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 175 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change(), and MSVehicle::setBlinkerInformation().
SUMOReal MSLCM_DK2004::getProb () const
Definition at line 666 of file MSLCM_DK2004.cpp.
References myChangeProbability.
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuouss lane change.
Returns
The vehicle's shadow lane
Definition at line 234 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSLane::executeMovements(), and MSVehicle::getPosition().
void * MSLCM_DK2004::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 604 of file MSLCM_DK2004.cpp.
References MSAbstractLaneChangeModel::myOwnState.
void MSLCM_DK2004::informBlocker (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int & blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow) protected
Definition at line 626 of file MSLCM_DK2004.cpp.
References ACCEL2DIST, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, MAX2(), MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, SPEED2DIST, and SUMOReal.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 255 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChanger::change(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSLane::executeMovements(), and MSVehicle::getAngle().
bool MSAbstractLaneChangeModel::isLaneChangeMidpointPassed () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 245 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeMidpointPassed.
Referenced by MSVehicle::getAngle(), MSVehicle::getPosition(), and MSVehicle::planMoveInternal().
SUMOReal MSLCM_DK2004::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 510 of file MSLCM_DK2004.cpp.
References bla, changed(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), GLO_VEHICLE, gSelected, GUISelectedStorage::isSelected(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_WANTS_LANECHANGE, MAX2(), MSCFModel::maxNextSpeed(), min, MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSCFModel::stopSpeed(), and SUMOReal.
bool MSAbstractLaneChangeModel::predInteraction (const MSVehicle *const leader) protected virtual inherited
Definition at line 86 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, and SUMOReal.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
void MSLCM_DK2004::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 655 of file MSLCM_DK2004.cpp.
References myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, and myVSafes.
void MSAbstractLaneChangeModel::removeLaneChangeShadow () inherited
remove the shadow copy of a lane change maneuver
Definition at line 181 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, and MSLane::removeVehicle().
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), and MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel().
virtual void MSAbstractLaneChangeModel::requestLaneChange (MSVehicle::ChangeRequest request) inline virtual inherited
The vehicle is requested to change the lane as soon as possible without violating any directives defined by this lane change model
Parameters
request indicates the requested change
Definition at line 302 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myChangeRequest.
Referenced by MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), and TraCIServerAPI_Vehicle::processSet().
void MSAbstractLaneChangeModel::resetMoved () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 270 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyMoved.
Referenced by MSVehicle::planMove().
void MSAbstractLaneChangeModel::setOwnState (int state) inline inherited
Definition at line 179 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change().
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 100 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), DELTA_T, MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), MSGlobals::gLaneChangeDuration, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLaneChangeMidpointPassed, MSAbstractLaneChangeModel::myLastLaneChangeOffset, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, and MSMoveReminder::NOTIFICATION_LANE_CHANGE.
Referenced by MSLaneChanger::startChange().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 227 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
int MSLCM_DK2004::wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked) virtual
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Implements MSAbstractLaneChangeModel.
Definition at line 301 of file MSLCM_DK2004.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, bla, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), GLO_VEHICLE, gSelected, informBlocker(), GUISelectedStorage::isSelected(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_LEFT, LCA_MLEFT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, MSAbstractLaneChangeModel::myChangeRequest, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), MSVehicle::REQUEST_LEFT, SUMO_const_haltingSpeed, and SUMOReal.
int MSLCM_DK2004::wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked) virtual
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Implements MSAbstractLaneChangeModel.
Definition at line 82 of file MSLCM_DK2004.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, bla, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), GLO_VEHICLE, gSelected, informBlocker(), GUISelectedStorage::isSelected(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_LEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, MSAbstractLaneChangeModel::myChangeRequest, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), MSVehicle::REQUEST_HOLD, MSVehicle::REQUEST_RIGHT, SUMO_const_haltingSpeed, and SUMOReal.
Field Documentation
bool MSAbstractLaneChangeModel::myAlreadyMoved protected inherited
whether the vehicle has already moved this step
Definition at line 345 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyMoved(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), and MSAbstractLaneChangeModel::resetMoved().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 358 of file MSAbstractLaneChangeModel.h.
Referenced by informBlocker(), MSAbstractLaneChangeModel::predInteraction(), wantsChangeToLeft(), and wantsChangeToRight().
SUMOReal MSLCM_DK2004::myChangeProbability protected
Definition at line 147 of file MSLCM_DK2004.h.
Referenced by changed(), getChangeProbability(), getProb(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
MSVehicle::ChangeRequest MSAbstractLaneChangeModel::myChangeRequest protected inherited
Definition at line 354 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::fulfillChangeRequest(), MSAbstractLaneChangeModel::requestLaneChange(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2004::myDontBrake protected
Definition at line 153 of file MSLCM_DK2004.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSAbstractLaneChangeModel::myHaveShadow protected inherited
Wether a vehicle shadow exists.
Definition at line 351 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 336 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getLaneChangeCompletion(), MSAbstractLaneChangeModel::isChangingLanes(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 339 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLaneChangeMidpointPassed protected inherited
whether myLane has already been set to the target of the lane-change maneuver
Definition at line 342 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::isLaneChangeMidpointPassed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::myLastLaneChangeOffset protected inherited
information how long ago the vehicle has performed a lane-change
Definition at line 333 of file MSAbstractLaneChangeModel.h.
Referenced by changed(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::getLastLaneChangeOffset(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::unchanged().
SUMOReal MSLCM_DK2004::myLeadingBlockerLength protected
Definition at line 149 of file MSLCM_DK2004.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
SUMOReal MSLCM_DK2004::myLeftSpace protected
Definition at line 150 of file MSLCM_DK2004.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 330 of file MSAbstractLaneChangeModel.h.
Referenced by amBlockingFollower(), amBlockingFollowerNB(), amBlockingFollowerPlusNB(), amBlockingLeader(), changed(), MSAbstractLaneChangeModel::getOwnState(), inform(), patchSpeed(), MSAbstractLaneChangeModel::setOwnState(), wantsChangeToLeft(), and wantsChangeToRight().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
The lane the vehicle shadow is on during a continuous lane change.
Definition at line 348 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 327 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), informBlocker(), patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), wantsChangeToLeft(), and wantsChangeToRight().
std::vector<SUMOReal> MSLCM_DK2004::myVSafes protected
Definition at line 152 of file MSLCM_DK2004.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
The documentation for this class was generated from the following files:
MSLCM_DK2004.h
MSLCM_DK2004.cpp