SUMO - Simulation of Urban MObility: StringBijection< T > Class Template Reference
StringBijection< T > Class Template Reference
#include <StringBijection.h>
Data Structures
struct Entry
Public Member Functions
T get (const std::string &str)
const std::string & getString (const T key)
std::vector< std::string > getStrings () const
bool has (const T key)
bool hasString (const std::string &str)
void insert (const std::string str, const T key)
size_t size () const
StringBijection ()
StringBijection (Entry entries[], T terminatorKey)
Private Attributes
std::map< std::string, T > myString2T
std::map< T, std::string > myT2String
Detailed Description
template<class T>
class StringBijection< T >
Template container for maintaining a bijection between strings and something else
Definition at line 47 of file StringBijection.h.
Constructor & Destructor Documentation
template<class T> StringBijection< T >::StringBijection () inline
Definition at line 64 of file StringBijection.h.
template<class T> StringBijection< T >::StringBijection (Entry entries[], T terminatorKey) inline
Definition at line 67 of file StringBijection.h.
Member Function Documentation
template<class T> T StringBijection< T >::get (const std::string & str) inline
Definition at line 81 of file StringBijection.h.
Referenced by NIImporter_SUMO::addEdge(), NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), NIVisumTL::build(), NGNode::buildNBNode(), NBNetBuilder::compute(), SUMOSAXAttributesImpl_Xerces::getEdgeFunc(), NWWriter_OpenDrive::getID(), SUMOSAXAttributesImpl_Xerces::getNodeType(), NBNodeCont::guessTLs(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NLHandler::initTrafficLightLogic(), NIImporter_OpenStreetMap::insertNodeChecking(), NLHandler::parseLinkDir(), NLHandler::parseLinkState(), NIXMLNodesHandler::processTrafficLightDefinitions(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), and NIXMLEdgesHandler::tryGetLaneSpread().
template<class T> const std::string& StringBijection< T >::getString (const T key) inline
Definition at line 90 of file StringBijection.h.
Referenced by toString< LaneSpreadFunction >(), toString< LinkDirection >(), toString< LinkState >(), toString< SumoXMLAttr >(), toString< SumoXMLEdgeFunc >(), toString< SumoXMLNodeType >(), toString< SumoXMLTag >(), toString< TrafficLightType >(), and NBSign::writeAsPOI().
template<class T> std::vector<std::string> StringBijection< T >::getStrings () const inline
Definition at line 115 of file StringBijection.h.
template<class T> bool StringBijection< T >::has (const T key) inline
Definition at line 105 of file StringBijection.h.
Referenced by StringBijection< TrafficLightType >::getString().
template<class T> bool StringBijection< T >::hasString (const std::string & str) inline
Definition at line 100 of file StringBijection.h.
Referenced by StringBijection< TrafficLightType >::get(), and NWWriter_OpenDrive::getID().
template<class T> void StringBijection< T >::insert (const std::string str, const T key) inline
Definition at line 75 of file StringBijection.h.
Referenced by NWWriter_OpenDrive::getID(), and StringBijection< TrafficLightType >::StringBijection().
template<class T> size_t StringBijection< T >::size () const inline
Definition at line 110 of file StringBijection.h.
Referenced by SUMOSAXAttributesImpl_Binary::getEdgeFunc(), and SUMOSAXAttributesImpl_Binary::getNodeType().
Field Documentation
template<class T> std::map<std::string, T> StringBijection< T >::myString2T private
Definition at line 126 of file StringBijection.h.
Referenced by StringBijection< TrafficLightType >::get(), StringBijection< TrafficLightType >::hasString(), StringBijection< TrafficLightType >::insert(), and StringBijection< TrafficLightType >::size().
template<class T> std::map<T, std::string> StringBijection< T >::myT2String private
Definition at line 127 of file StringBijection.h.
Referenced by StringBijection< TrafficLightType >::getString(), StringBijection< TrafficLightType >::getStrings(), StringBijection< TrafficLightType >::has(), and StringBijection< TrafficLightType >::insert().
The documentation for this class was generated from the following file:
StringBijection.h